// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/assetmgmt/v1/location_info.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LocationInfo encodes the physical location of an asset with building,
// floor, and zone identifiers. This serves as the primary location binding
// for location-based access control policies.
type LocationInfo struct {
	// building_id is the unique identifier for the building/facility.
	// This is the primary location scope identifier.
	BuildingId string `protobuf:"bytes,1,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	// floor_id is the unique identifier for the floor within the building.
	FloorId string `protobuf:"bytes,2,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
	// zone_id is the unique identifier for the zone/area on the floor.
	ZoneId string `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	// latitude_microdegrees is the latitude in microdegrees (degrees * 1e6)
	// Range: -90000000 to 90000000 (~0.11 meter precision)
	// Use fixed-point representation to ensure deterministic state across all nodes.
	// To convert: degrees * 1000000 = microdegrees
	LatitudeMicrodegrees int64 `protobuf:"varint,4,opt,name=latitude_microdegrees,json=latitudeMicrodegrees,proto3" json:"latitude_microdegrees,omitempty"`
	// longitude_microdegrees is the longitude in microdegrees (degrees * 1e6)
	// Range: -180000000 to 180000000
	// Use fixed-point representation to ensure deterministic state across all nodes.
	// To convert: degrees * 1000000 = microdegrees
	LongitudeMicrodegrees int64 `protobuf:"varint,5,opt,name=longitude_microdegrees,json=longitudeMicrodegrees,proto3" json:"longitude_microdegrees,omitempty"`
}

func (m *LocationInfo) Reset()         { *m = LocationInfo{} }
func (m *LocationInfo) String() string { return proto.CompactTextString(m) }
func (*LocationInfo) ProtoMessage()    {}
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c289ebfe799ef6a, []int{0}
}
func (m *LocationInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LocationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LocationInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LocationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationInfo.Merge(m, src)
}
func (m *LocationInfo) XXX_Size() int {
	return m.Size()
}
func (m *LocationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LocationInfo proto.InternalMessageInfo

func (m *LocationInfo) GetBuildingId() string {
	if m != nil {
		return m.BuildingId
	}
	return ""
}

func (m *LocationInfo) GetFloorId() string {
	if m != nil {
		return m.FloorId
	}
	return ""
}

func (m *LocationInfo) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *LocationInfo) GetLatitudeMicrodegrees() int64 {
	if m != nil {
		return m.LatitudeMicrodegrees
	}
	return 0
}

func (m *LocationInfo) GetLongitudeMicrodegrees() int64 {
	if m != nil {
		return m.LongitudeMicrodegrees
	}
	return 0
}

func init() {
	proto.RegisterType((*LocationInfo)(nil), "acmain.assetmgmt.v1.LocationInfo")
}

func init() {
	proto.RegisterFile("acmain/assetmgmt/v1/location_info.proto", fileDescriptor_8c289ebfe799ef6a)
}

var fileDescriptor_8c289ebfe799ef6a = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x4c, 0xce, 0x4d,
	0xcc, 0xcc, 0xd3, 0x4f, 0x2c, 0x2e, 0x4e, 0x2d, 0xc9, 0x4d, 0xcf, 0x2d, 0xd1, 0x2f, 0x33, 0xd4,
	0xcf, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x86, 0x28, 0xd4, 0x83, 0x2b, 0xd4, 0x2b, 0x33, 0x94, 0x12, 0x49,
	0xcf, 0x4f, 0xcf, 0x07, 0xcb, 0xeb, 0x83, 0x58, 0x10, 0xa5, 0x4a, 0x57, 0x19, 0xb9, 0x78, 0x7c,
	0xa0, 0x46, 0x78, 0xe6, 0xa5, 0xe5, 0x0b, 0xc9, 0x73, 0x71, 0x27, 0x95, 0x66, 0xe6, 0xa4, 0x64,
	0xe6, 0xa5, 0xc7, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0xc1, 0x84, 0x3c,
	0x53, 0x84, 0x24, 0xb9, 0x38, 0xd2, 0x72, 0xf2, 0xf3, 0x8b, 0x40, 0xb2, 0x4c, 0x60, 0x59, 0x76,
	0x30, 0xdf, 0x33, 0x45, 0x48, 0x9c, 0x8b, 0xbd, 0x2a, 0x3f, 0x2f, 0x15, 0x24, 0xc3, 0x0c, 0x96,
	0x61, 0x03, 0x71, 0x3d, 0x53, 0x84, 0x8c, 0xb9, 0x44, 0x73, 0x12, 0x4b, 0x32, 0x4b, 0x4a, 0x53,
	0x52, 0xe3, 0x73, 0x33, 0x93, 0x8b, 0xf2, 0x53, 0x52, 0xd3, 0x8b, 0x52, 0x53, 0x8b, 0x25, 0x58,
	0x14, 0x18, 0x35, 0x98, 0x83, 0x44, 0x60, 0x92, 0xbe, 0x48, 0x72, 0x42, 0xa6, 0x5c, 0x62, 0x39,
	0xf9, 0x79, 0xe9, 0x58, 0x74, 0xb1, 0x82, 0x75, 0x89, 0xc2, 0x65, 0x91, 0xb5, 0x59, 0xb1, 0xbc,
	0x58, 0x20, 0xcf, 0xe8, 0x64, 0x74, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e,
	0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51,
	0x12, 0xd0, 0x50, 0xac, 0x40, 0x0a, 0xc7, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0x70, 0x90,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xc7, 0x5b, 0xb1, 0x68, 0x01, 0x00, 0x00,
}

func (this *LocationInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LocationInfo)
	if !ok {
		that2, ok := that.(LocationInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BuildingId != that1.BuildingId {
		return false
	}
	if this.FloorId != that1.FloorId {
		return false
	}
	if this.ZoneId != that1.ZoneId {
		return false
	}
	if this.LatitudeMicrodegrees != that1.LatitudeMicrodegrees {
		return false
	}
	if this.LongitudeMicrodegrees != that1.LongitudeMicrodegrees {
		return false
	}
	return true
}
func (m *LocationInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LocationInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LocationInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LongitudeMicrodegrees != 0 {
		i = encodeVarintLocationInfo(dAtA, i, uint64(m.LongitudeMicrodegrees))
		i--
		dAtA[i] = 0x28
	}
	if m.LatitudeMicrodegrees != 0 {
		i = encodeVarintLocationInfo(dAtA, i, uint64(m.LatitudeMicrodegrees))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ZoneId) > 0 {
		i -= len(m.ZoneId)
		copy(dAtA[i:], m.ZoneId)
		i = encodeVarintLocationInfo(dAtA, i, uint64(len(m.ZoneId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FloorId) > 0 {
		i -= len(m.FloorId)
		copy(dAtA[i:], m.FloorId)
		i = encodeVarintLocationInfo(dAtA, i, uint64(len(m.FloorId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BuildingId) > 0 {
		i -= len(m.BuildingId)
		copy(dAtA[i:], m.BuildingId)
		i = encodeVarintLocationInfo(dAtA, i, uint64(len(m.BuildingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLocationInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovLocationInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LocationInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BuildingId)
	if l > 0 {
		n += 1 + l + sovLocationInfo(uint64(l))
	}
	l = len(m.FloorId)
	if l > 0 {
		n += 1 + l + sovLocationInfo(uint64(l))
	}
	l = len(m.ZoneId)
	if l > 0 {
		n += 1 + l + sovLocationInfo(uint64(l))
	}
	if m.LatitudeMicrodegrees != 0 {
		n += 1 + sovLocationInfo(uint64(m.LatitudeMicrodegrees))
	}
	if m.LongitudeMicrodegrees != 0 {
		n += 1 + sovLocationInfo(uint64(m.LongitudeMicrodegrees))
	}
	return n
}

func sovLocationInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLocationInfo(x uint64) (n int) {
	return sovLocationInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LocationInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocationInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LocationInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LocationInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuildingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocationInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocationInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuildingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FloorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocationInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocationInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FloorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZoneId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocationInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocationInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZoneId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatitudeMicrodegrees", wireType)
			}
			m.LatitudeMicrodegrees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatitudeMicrodegrees |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LongitudeMicrodegrees", wireType)
			}
			m.LongitudeMicrodegrees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LongitudeMicrodegrees |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLocationInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocationInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLocationInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLocationInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocationInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLocationInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLocationInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLocationInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLocationInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLocationInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLocationInfo = fmt.Errorf("proto: unexpected end of group")
)
