// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/credential.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CredentialProof represents the cryptographic proof of a verifiable credential
type CredentialProof struct {
	// type is the proof type (e.g., "Ed25519Signature2020")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// created_at is when the proof was created
	CreatedAt time.Time `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// verification_method is the DID method used to verify (e.g., "#key-1")
	VerificationMethod string `protobuf:"bytes,3,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	// proof_value is the signature bytes (base64 encoded in JSON)
	ProofValue []byte `protobuf:"bytes,4,opt,name=proof_value,json=proofValue,proto3" json:"proof_value,omitempty"`
}

func (m *CredentialProof) Reset()         { *m = CredentialProof{} }
func (m *CredentialProof) String() string { return proto.CompactTextString(m) }
func (*CredentialProof) ProtoMessage()    {}
func (*CredentialProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3a2047da0265d7, []int{0}
}
func (m *CredentialProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CredentialProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CredentialProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CredentialProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialProof.Merge(m, src)
}
func (m *CredentialProof) XXX_Size() int {
	return m.Size()
}
func (m *CredentialProof) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialProof.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialProof proto.InternalMessageInfo

func (m *CredentialProof) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CredentialProof) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *CredentialProof) GetVerificationMethod() string {
	if m != nil {
		return m.VerificationMethod
	}
	return ""
}

func (m *CredentialProof) GetProofValue() []byte {
	if m != nil {
		return m.ProofValue
	}
	return nil
}

// CredentialSubject represents the subject of a verifiable credential
type CredentialSubject struct {
	// id is the DID of the subject
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// claims are key-value attribute pairs (e.g., "role": "engineer", "department": "ops")
	Claims map[string]string `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *CredentialSubject) Reset()         { *m = CredentialSubject{} }
func (m *CredentialSubject) String() string { return proto.CompactTextString(m) }
func (*CredentialSubject) ProtoMessage()    {}
func (*CredentialSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3a2047da0265d7, []int{1}
}
func (m *CredentialSubject) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CredentialSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CredentialSubject.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CredentialSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialSubject.Merge(m, src)
}
func (m *CredentialSubject) XXX_Size() int {
	return m.Size()
}
func (m *CredentialSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialSubject.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialSubject proto.InternalMessageInfo

func (m *CredentialSubject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CredentialSubject) GetClaims() map[string]string {
	if m != nil {
		return m.Claims
	}
	return nil
}

// CredentialStatusInfo tracks the status of a credential
type CredentialStatusInfo struct {
	// status is the current status of the credential
	Status CredentialStatus `protobuf:"varint,1,opt,name=status,proto3,enum=acmain.iam.v1.CredentialStatus" json:"status,omitempty"`
	// updated_at is when the status was last updated
	UpdatedAt time.Time `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	// revocation_reason describes why the credential was revoked/suspended
	RevocationReason string `protobuf:"bytes,3,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
}

func (m *CredentialStatusInfo) Reset()         { *m = CredentialStatusInfo{} }
func (m *CredentialStatusInfo) String() string { return proto.CompactTextString(m) }
func (*CredentialStatusInfo) ProtoMessage()    {}
func (*CredentialStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f3a2047da0265d7, []int{2}
}
func (m *CredentialStatusInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CredentialStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CredentialStatusInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CredentialStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialStatusInfo.Merge(m, src)
}
func (m *CredentialStatusInfo) XXX_Size() int {
	return m.Size()
}
func (m *CredentialStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialStatusInfo proto.InternalMessageInfo

func (m *CredentialStatusInfo) GetStatus() CredentialStatus {
	if m != nil {
		return m.Status
	}
	return CREDENTIAL_STATUS_UNSPECIFIED
}

func (m *CredentialStatusInfo) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *CredentialStatusInfo) GetRevocationReason() string {
	if m != nil {
		return m.RevocationReason
	}
	return ""
}

func init() {
	proto.RegisterType((*CredentialProof)(nil), "acmain.iam.v1.CredentialProof")
	proto.RegisterType((*CredentialSubject)(nil), "acmain.iam.v1.CredentialSubject")
	proto.RegisterMapType((map[string]string)(nil), "acmain.iam.v1.CredentialSubject.ClaimsEntry")
	proto.RegisterType((*CredentialStatusInfo)(nil), "acmain.iam.v1.CredentialStatusInfo")
}

func init() { proto.RegisterFile("acmain/iam/v1/credential.proto", fileDescriptor_1f3a2047da0265d7) }

var fileDescriptor_1f3a2047da0265d7 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xcf, 0x39, 0x25, 0x52, 0x5f, 0x68, 0x69, 0x8e, 0x0c, 0x26, 0x42, 0x76, 0x1a, 0x24, 0x14,
	0x95, 0xea, 0xac, 0x86, 0x01, 0xc8, 0xd6, 0x16, 0x24, 0x18, 0x90, 0x90, 0x41, 0x0c, 0x2c, 0xd1,
	0xc5, 0xbe, 0x84, 0x03, 0x9f, 0xcf, 0xb2, 0xcf, 0x16, 0xf9, 0x0a, 0x4c, 0xfd, 0x18, 0x8c, 0xfd,
	0x18, 0x65, 0xeb, 0xc8, 0x04, 0x28, 0x41, 0xea, 0xc6, 0x67, 0x40, 0x3e, 0x5f, 0xdb, 0x04, 0x94,
	0x85, 0xc5, 0x7a, 0xef, 0xf7, 0x7e, 0xef, 0xcf, 0xef, 0x7e, 0x06, 0x87, 0x06, 0x82, 0xf2, 0xd8,
	0xe3, 0x54, 0x78, 0xc5, 0x81, 0x17, 0xa4, 0x2c, 0x64, 0xb1, 0xe2, 0x34, 0x22, 0x49, 0x2a, 0x95,
	0xc4, 0x5b, 0x55, 0x9d, 0x70, 0x2a, 0x48, 0x71, 0xd0, 0xb9, 0xb3, 0x4a, 0x67, 0x71, 0x2e, 0xb2,
	0x8a, 0xd9, 0x69, 0x51, 0xc1, 0x63, 0xe9, 0xe9, 0xaf, 0x81, 0xda, 0x53, 0x39, 0x95, 0x3a, 0xf4,
	0xca, 0xc8, 0xa0, 0xee, 0x54, 0xca, 0x69, 0xc4, 0x3c, 0x9d, 0x8d, 0xf3, 0x89, 0xa7, 0xb8, 0x60,
	0x99, 0xa2, 0x22, 0xa9, 0x08, 0xbd, 0x5f, 0x08, 0x6e, 0x1d, 0x5f, 0x1d, 0xf2, 0x2a, 0x95, 0x72,
	0x82, 0x31, 0x6c, 0xa8, 0x59, 0xc2, 0x6c, 0xd4, 0x45, 0xfd, 0x4d, 0x5f, 0xc7, 0xf8, 0x39, 0x40,
	0x90, 0x32, 0xaa, 0x58, 0x38, 0xa2, 0xca, 0xb6, 0xba, 0xa8, 0xdf, 0x1c, 0x74, 0x48, 0x35, 0x9d,
	0x5c, 0x4e, 0x27, 0x6f, 0x2e, 0xa7, 0x1f, 0x6d, 0x9d, 0x7d, 0x77, 0x6b, 0x27, 0x3f, 0x5c, 0xf4,
	0xe5, 0xe2, 0x74, 0x0f, 0xf9, 0x9b, 0xa6, 0xf9, 0x50, 0x61, 0x0f, 0x6e, 0x17, 0x2c, 0xe5, 0x13,
	0x1e, 0x50, 0xc5, 0x65, 0x3c, 0x12, 0x4c, 0xbd, 0x97, 0xa1, 0x5d, 0xd7, 0xcb, 0xf0, 0x72, 0xe9,
	0xa5, 0xae, 0x60, 0x17, 0x9a, 0x49, 0x79, 0xd7, 0xa8, 0xa0, 0x51, 0xce, 0xec, 0x8d, 0x2e, 0xea,
	0xdf, 0xf4, 0x41, 0x43, 0x6f, 0x4b, 0x64, 0xb8, 0xfb, 0xf9, 0xe2, 0x74, 0xef, 0xae, 0x79, 0xad,
	0x4f, 0xfa, 0xbd, 0xfe, 0x92, 0xd4, 0xfb, 0x8a, 0xa0, 0x75, 0x8d, 0xbd, 0xce, 0xc7, 0x1f, 0x58,
	0xa0, 0xf0, 0x36, 0x58, 0x3c, 0x34, 0x32, 0x2d, 0x1e, 0xe2, 0xa7, 0xd0, 0x08, 0x22, 0xca, 0x45,
	0x66, 0x5b, 0xdd, 0x7a, 0xbf, 0x39, 0xd8, 0x27, 0x2b, 0x8e, 0x90, 0x7f, 0x26, 0x90, 0x63, 0x4d,
	0x7f, 0x16, 0xab, 0x74, 0xe6, 0x9b, 0xde, 0xce, 0x13, 0x68, 0x2e, 0xc1, 0x78, 0x07, 0xea, 0x1f,
	0xd9, 0xcc, 0x6c, 0x29, 0x43, 0xdc, 0x86, 0x1b, 0x95, 0x14, 0x4b, 0x63, 0x55, 0x32, 0xb4, 0x1e,
	0xa3, 0xe1, 0xbd, 0x52, 0x89, 0xb3, 0x46, 0x89, 0xd9, 0xd9, 0xfb, 0x8d, 0xa0, 0xbd, 0x84, 0x2a,
	0xaa, 0xf2, 0xec, 0x45, 0x3c, 0x91, 0xf8, 0x11, 0x34, 0x32, 0x9d, 0xe9, 0x65, 0xdb, 0x03, 0x77,
	0xfd, 0xf9, 0x9a, 0xe6, 0x1b, 0x7a, 0x69, 0x6e, 0x9e, 0x84, 0xff, 0x6f, 0xae, 0x69, 0x3e, 0x54,
	0xf8, 0x01, 0xb4, 0x52, 0x56, 0x48, 0x63, 0x6d, 0xca, 0x68, 0x26, 0x63, 0x63, 0xed, 0xce, 0x75,
	0xc1, 0xd7, 0xf8, 0xf0, 0x7e, 0xa9, 0x76, 0x77, 0x9d, 0xda, 0x2b, 0x5d, 0x47, 0xfb, 0x67, 0x73,
	0x07, 0x9d, 0xcf, 0x1d, 0xf4, 0x73, 0xee, 0xa0, 0x93, 0x85, 0x53, 0x3b, 0x5f, 0x38, 0xb5, 0x6f,
	0x0b, 0xa7, 0xf6, 0x0e, 0xaf, 0x34, 0x97, 0x3f, 0x6a, 0x36, 0x6e, 0xe8, 0x83, 0x1f, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x99, 0xef, 0xd4, 0x6e, 0x03, 0x00, 0x00,
}

func (m *CredentialProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CredentialProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CredentialProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProofValue) > 0 {
		i -= len(m.ProofValue)
		copy(dAtA[i:], m.ProofValue)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.ProofValue)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VerificationMethod) > 0 {
		i -= len(m.VerificationMethod)
		copy(dAtA[i:], m.VerificationMethod)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.VerificationMethod)))
		i--
		dAtA[i] = 0x1a
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintCredential(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CredentialSubject) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CredentialSubject) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CredentialSubject) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Claims) > 0 {
		for k := range m.Claims {
			v := m.Claims[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCredential(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCredential(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCredential(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CredentialStatusInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CredentialStatusInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CredentialStatusInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RevocationReason) > 0 {
		i -= len(m.RevocationReason)
		copy(dAtA[i:], m.RevocationReason)
		i = encodeVarintCredential(dAtA, i, uint64(len(m.RevocationReason)))
		i--
		dAtA[i] = 0x1a
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintCredential(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if m.Status != 0 {
		i = encodeVarintCredential(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCredential(dAtA []byte, offset int, v uint64) int {
	offset -= sovCredential(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CredentialProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovCredential(uint64(l))
	l = len(m.VerificationMethod)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	l = len(m.ProofValue)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	return n
}

func (m *CredentialSubject) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	if len(m.Claims) > 0 {
		for k, v := range m.Claims {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCredential(uint64(len(k))) + 1 + len(v) + sovCredential(uint64(len(v)))
			n += mapEntrySize + 1 + sovCredential(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *CredentialStatusInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovCredential(uint64(m.Status))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovCredential(uint64(l))
	l = len(m.RevocationReason)
	if l > 0 {
		n += 1 + l + sovCredential(uint64(l))
	}
	return n
}

func sovCredential(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCredential(x uint64) (n int) {
	return sovCredential(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CredentialProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CredentialProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CredentialProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofValue = append(m.ProofValue[:0], dAtA[iNdEx:postIndex]...)
			if m.ProofValue == nil {
				m.ProofValue = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CredentialSubject) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CredentialSubject: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CredentialSubject: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Claims == nil {
				m.Claims = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCredential
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCredential
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCredential
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCredential
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCredential
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCredential
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCredential
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCredential(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCredential
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Claims[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CredentialStatusInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CredentialStatusInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CredentialStatusInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CredentialStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevocationReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevocationReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCredential(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCredential
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCredential
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCredential
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCredential
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCredential        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCredential          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCredential = fmt.Errorf("proto: unexpected end of group")
)
