// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/device_key.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DeviceKey represents a registered device's public key information
type DeviceKey struct {
	// device_id is the unique identifier for the IoT device
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// public_key is the device's public key
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// key_type is the cryptographic algorithm
	KeyType KeyType `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=acmain.iam.v1.KeyType" json:"key_type,omitempty"`
	// owner is the Cosmos address that owns this device
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// device_type describes the device category (e.g., "smart_lock", "sensor", "witness_node")
	DeviceType string `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// location is where the device is physically located
	Location string `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	// registered_at is the block timestamp of registration
	RegisteredAt time.Time `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3,stdtime" json:"registered_at"`
	// last_rotation_at is the timestamp of last key rotation
	LastRotationAt *time.Time `protobuf:"bytes,8,opt,name=last_rotation_at,json=lastRotationAt,proto3,stdtime" json:"last_rotation_at,omitempty"`
	// revoked_at indicates if/when the key was revoked
	RevokedAt *time.Time `protobuf:"bytes,9,opt,name=revoked_at,json=revokedAt,proto3,stdtime" json:"revoked_at,omitempty"`
	// metadata stores device-specific attributes
	Metadata map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// active indicates if the device key is currently active
	Active bool `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
}

func (m *DeviceKey) Reset()         { *m = DeviceKey{} }
func (m *DeviceKey) String() string { return proto.CompactTextString(m) }
func (*DeviceKey) ProtoMessage()    {}
func (*DeviceKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_558fa66e64dbb23e, []int{0}
}
func (m *DeviceKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceKey.Merge(m, src)
}
func (m *DeviceKey) XXX_Size() int {
	return m.Size()
}
func (m *DeviceKey) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceKey.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceKey proto.InternalMessageInfo

func (m *DeviceKey) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *DeviceKey) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KEY_TYPE_UNSPECIFIED
}

func (m *DeviceKey) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeviceKey) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceKey) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *DeviceKey) GetRegisteredAt() time.Time {
	if m != nil {
		return m.RegisteredAt
	}
	return time.Time{}
}

func (m *DeviceKey) GetLastRotationAt() *time.Time {
	if m != nil {
		return m.LastRotationAt
	}
	return nil
}

func (m *DeviceKey) GetRevokedAt() *time.Time {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func (m *DeviceKey) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DeviceKey) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*DeviceKey)(nil), "acmain.iam.v1.DeviceKey")
	proto.RegisterMapType((map[string]string)(nil), "acmain.iam.v1.DeviceKey.MetadataEntry")
}

func init() { proto.RegisterFile("acmain/iam/v1/device_key.proto", fileDescriptor_558fa66e64dbb23e) }

var fileDescriptor_558fa66e64dbb23e = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xcf, 0x35, 0x7f, 0x6a, 0x5f, 0x9a, 0xaa, 0x9c, 0xa2, 0xc8, 0x4d, 0x85, 0x63, 0x31, 0x20,
	0xab, 0x02, 0x5b, 0x09, 0x0b, 0x2a, 0x03, 0x4a, 0x04, 0x03, 0x54, 0x30, 0x98, 0x4e, 0x2c, 0xd1,
	0xc5, 0x3e, 0xac, 0x53, 0x62, 0x9f, 0x65, 0x5f, 0x0c, 0xfe, 0x0a, 0x4c, 0xfd, 0x18, 0x8c, 0x1d,
	0xf8, 0x10, 0x1d, 0x2b, 0x26, 0x26, 0x40, 0xc9, 0xd0, 0xef, 0xc0, 0x84, 0xee, 0x4f, 0x82, 0xc2,
	0x42, 0x17, 0xeb, 0xfd, 0x7e, 0x7e, 0xbf, 0xf7, 0x7e, 0xef, 0xdd, 0x83, 0x36, 0x0e, 0x13, 0x4c,
	0x53, 0x9f, 0xe2, 0xc4, 0x2f, 0x87, 0x7e, 0x44, 0x4a, 0x1a, 0x92, 0xe9, 0x9c, 0x54, 0x5e, 0x96,
	0x33, 0xce, 0x50, 0x47, 0xfd, 0xf7, 0x28, 0x4e, 0xbc, 0x72, 0xd8, 0x3f, 0xde, 0x4d, 0x27, 0xe9,
	0x32, 0x29, 0x54, 0x66, 0xff, 0x1e, 0x4e, 0x68, 0xca, 0x7c, 0xf9, 0xd5, 0xd4, 0x71, 0xc8, 0x8a,
	0x84, 0x15, 0x53, 0x89, 0x7c, 0x05, 0xf4, 0xaf, 0x6e, 0xcc, 0x62, 0xa6, 0x78, 0x11, 0x69, 0x76,
	0x10, 0x33, 0x16, 0x2f, 0x88, 0x2f, 0xd1, 0x6c, 0xf9, 0xc1, 0xe7, 0x34, 0x21, 0x05, 0xc7, 0x49,
	0xa6, 0x12, 0x1e, 0xfc, 0x6e, 0x40, 0xf3, 0x85, 0xf4, 0x78, 0x4e, 0x2a, 0x74, 0x02, 0x4d, 0x6d,
	0x98, 0x46, 0x16, 0x70, 0x80, 0x6b, 0x06, 0x86, 0x22, 0x5e, 0x45, 0xe8, 0x3e, 0x84, 0xd9, 0x72,
	0xb6, 0xa0, 0xa1, 0x98, 0xc6, 0xda, 0x73, 0x80, 0x7b, 0x10, 0x98, 0x8a, 0x11, 0xda, 0x21, 0x34,
	0xe6, 0xa4, 0x9a, 0xf2, 0x2a, 0x23, 0x56, 0xdd, 0x01, 0xee, 0xe1, 0xa8, 0xe7, 0xed, 0xcc, 0xea,
	0x9d, 0x93, 0xea, 0xa2, 0xca, 0x48, 0xb0, 0x3f, 0x57, 0x01, 0xf2, 0x60, 0x93, 0x7d, 0x4c, 0x49,
	0x6e, 0x35, 0x44, 0xab, 0x89, 0xf5, 0xed, 0xeb, 0xe3, 0xae, 0x1e, 0x6a, 0x1c, 0x45, 0x39, 0x29,
	0x8a, 0x77, 0x3c, 0xa7, 0x69, 0x1c, 0xa8, 0x34, 0x34, 0x80, 0x6d, 0x6d, 0x4f, 0x76, 0x69, 0x4a,
	0x83, 0x50, 0x51, 0xb2, 0x60, 0x1f, 0x1a, 0x0b, 0x16, 0x62, 0x4e, 0x59, 0x6a, 0xb5, 0x94, 0xfd,
	0x0d, 0x46, 0x6f, 0x61, 0x27, 0x27, 0x31, 0x2d, 0x38, 0xc9, 0x49, 0x34, 0xc5, 0xdc, 0xda, 0x77,
	0x80, 0xdb, 0x1e, 0xf5, 0x3d, 0xb5, 0x22, 0x6f, 0xb3, 0x22, 0xef, 0x62, 0xb3, 0xa2, 0x49, 0xe7,
	0xfa, 0xc7, 0xa0, 0x76, 0xf9, 0x73, 0x00, 0xbe, 0xdc, 0x5e, 0x9d, 0x82, 0xe0, 0xe0, 0xaf, 0x7e,
	0xcc, 0xd1, 0x6b, 0x78, 0xb4, 0xc0, 0x05, 0x9f, 0xe6, 0x8c, 0xcb, 0x06, 0xa2, 0xa4, 0xf1, 0xdf,
	0x92, 0x0d, 0x51, 0x2e, 0x38, 0x14, 0xca, 0x40, 0x0b, 0xc7, 0x1c, 0x3d, 0x87, 0x30, 0x27, 0x25,
	0x9b, 0x2b, 0x63, 0xe6, 0x1d, 0xab, 0x98, 0x5a, 0x33, 0xe6, 0x68, 0x02, 0x8d, 0x84, 0x70, 0x1c,
	0x61, 0x8e, 0x2d, 0xe8, 0xd4, 0xdd, 0xf6, 0xe8, 0xe1, 0x3f, 0xcb, 0xdf, 0x3e, 0xb2, 0xf7, 0x46,
	0x27, 0xbe, 0x4c, 0x79, 0x5e, 0x05, 0x5b, 0x1d, 0xea, 0xc1, 0x16, 0x0e, 0x39, 0x2d, 0x89, 0xd5,
	0x76, 0x80, 0x6b, 0x04, 0x1a, 0xf5, 0x9f, 0xc1, 0xce, 0x8e, 0x04, 0x1d, 0xc1, 0xba, 0xb8, 0x00,
	0x75, 0x1f, 0x22, 0x44, 0x5d, 0xd8, 0x2c, 0xf1, 0x62, 0x49, 0xe4, 0x55, 0x98, 0x81, 0x02, 0x67,
	0x7b, 0x4f, 0xc1, 0xd9, 0xc9, 0xe7, 0xdb, 0xab, 0xd3, 0x9e, 0x3e, 0xf2, 0x4f, 0xf2, 0xcc, 0xb7,
	0x4e, 0x26, 0x8f, 0xae, 0x57, 0x36, 0xb8, 0x59, 0xd9, 0xe0, 0xd7, 0xca, 0x06, 0x97, 0x6b, 0xbb,
	0x76, 0xb3, 0xb6, 0x6b, 0xdf, 0xd7, 0x76, 0xed, 0x3d, 0xda, 0x51, 0x88, 0xd7, 0x2e, 0x66, 0x2d,
	0xb9, 0x88, 0x27, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xb1, 0x73, 0xa2, 0x62, 0x03, 0x00,
	0x00,
}

func (m *DeviceKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintDeviceKey(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintDeviceKey(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintDeviceKey(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.RevokedAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RevokedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintDeviceKey(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x4a
	}
	if m.LastRotationAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastRotationAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastRotationAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintDeviceKey(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x42
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.RegisteredAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintDeviceKey(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x3a
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintDeviceKey(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DeviceType) > 0 {
		i -= len(m.DeviceType)
		copy(dAtA[i:], m.DeviceType)
		i = encodeVarintDeviceKey(dAtA, i, uint64(len(m.DeviceType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintDeviceKey(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if m.KeyType != 0 {
		i = encodeVarintDeviceKey(dAtA, i, uint64(m.KeyType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintDeviceKey(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintDeviceKey(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeviceKey(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeviceKey(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DeviceKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	if m.KeyType != 0 {
		n += 1 + sovDeviceKey(uint64(m.KeyType))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	l = len(m.DeviceType)
	if l > 0 {
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.RegisteredAt)
	n += 1 + l + sovDeviceKey(uint64(l))
	if m.LastRotationAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastRotationAt)
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	if m.RevokedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt)
		n += 1 + l + sovDeviceKey(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovDeviceKey(uint64(len(k))) + 1 + len(v) + sovDeviceKey(uint64(len(v)))
			n += mapEntrySize + 1 + sovDeviceKey(uint64(mapEntrySize))
		}
	}
	if m.Active {
		n += 2
	}
	return n
}

func sovDeviceKey(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeviceKey(x uint64) (n int) {
	return sovDeviceKey(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DeviceKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeviceKey
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			m.KeyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyType |= KeyType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.RegisteredAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRotationAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastRotationAt == nil {
				m.LastRotationAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastRotationAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RevokedAt == nil {
				m.RevokedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RevokedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDeviceKey
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowDeviceKey
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDeviceKey
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthDeviceKey
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthDeviceKey
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowDeviceKey
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthDeviceKey
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthDeviceKey
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipDeviceKey(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthDeviceKey
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipDeviceKey(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeviceKey
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeviceKey(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeviceKey
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeviceKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeviceKey
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeviceKey
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeviceKey
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeviceKey        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeviceKey          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeviceKey = fmt.Errorf("proto: unexpected end of group")
)
