// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/did_document.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DIDDocument represents a W3C-compliant DID Document adapted for Cosmos
// This is the canonical form stored on-chain
type DIDDocument struct {
	// id is the DID itself (e.g., "did:acmain:cosmos1abcdef...")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// context defines the JSON-LD context (stored as strings for protobuf)
	Context []string `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	// controller is the address that can update this DID document
	Controller string `protobuf:"bytes,3,opt,name=controller,proto3" json:"controller,omitempty"`
	// public_keys are all public keys associated with this DID
	PublicKeys []PublicKeyInfo `protobuf:"bytes,4,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys"`
	// verification_relationships define how keys are used
	VerificationRelationships []VerificationRelationship `protobuf:"bytes,5,rep,name=verification_relationships,json=verificationRelationships,proto3" json:"verification_relationships"`
	// service_endpoints describe external services (e.g., website, API endpoints)
	ServiceEndpoints []ServiceEndpoint `protobuf:"bytes,6,rep,name=service_endpoints,json=serviceEndpoints,proto3" json:"service_endpoints"`
	// also_known_as provides alternative identifiers
	AlsoKnownAs []string `protobuf:"bytes,7,rep,name=also_known_as,json=alsoKnownAs,proto3" json:"also_known_as,omitempty"`
	// created_at is the block timestamp when the DID was created
	CreatedAt time.Time `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// updated_at is the block timestamp of the last update
	UpdatedAt time.Time `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	// deactivated indicates if the DID is deactivated
	Deactivated bool `protobuf:"varint,10,opt,name=deactivated,proto3" json:"deactivated,omitempty"`
	// deactivated_at is the block timestamp when the DID was deactivated
	DeactivatedAt *time.Time `protobuf:"bytes,11,opt,name=deactivated_at,json=deactivatedAt,proto3,stdtime" json:"deactivated_at,omitempty"`
	// did_method specifies which DID method is used
	DidMethod DIDMethod `protobuf:"varint,12,opt,name=did_method,json=didMethod,proto3,enum=acmain.iam.v1.DIDMethod" json:"did_method,omitempty"`
}

func (m *DIDDocument) Reset()         { *m = DIDDocument{} }
func (m *DIDDocument) String() string { return proto.CompactTextString(m) }
func (*DIDDocument) ProtoMessage()    {}
func (*DIDDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_696ca1996ae783df, []int{0}
}
func (m *DIDDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DIDDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DIDDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DIDDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DIDDocument.Merge(m, src)
}
func (m *DIDDocument) XXX_Size() int {
	return m.Size()
}
func (m *DIDDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_DIDDocument.DiscardUnknown(m)
}

var xxx_messageInfo_DIDDocument proto.InternalMessageInfo

func (m *DIDDocument) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DIDDocument) GetContext() []string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *DIDDocument) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *DIDDocument) GetPublicKeys() []PublicKeyInfo {
	if m != nil {
		return m.PublicKeys
	}
	return nil
}

func (m *DIDDocument) GetVerificationRelationships() []VerificationRelationship {
	if m != nil {
		return m.VerificationRelationships
	}
	return nil
}

func (m *DIDDocument) GetServiceEndpoints() []ServiceEndpoint {
	if m != nil {
		return m.ServiceEndpoints
	}
	return nil
}

func (m *DIDDocument) GetAlsoKnownAs() []string {
	if m != nil {
		return m.AlsoKnownAs
	}
	return nil
}

func (m *DIDDocument) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *DIDDocument) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *DIDDocument) GetDeactivated() bool {
	if m != nil {
		return m.Deactivated
	}
	return false
}

func (m *DIDDocument) GetDeactivatedAt() *time.Time {
	if m != nil {
		return m.DeactivatedAt
	}
	return nil
}

func (m *DIDDocument) GetDidMethod() DIDMethod {
	if m != nil {
		return m.DidMethod
	}
	return DID_METHOD_UNSPECIFIED
}

func init() {
	proto.RegisterType((*DIDDocument)(nil), "acmain.iam.v1.DIDDocument")
}

func init() { proto.RegisterFile("acmain/iam/v1/did_document.proto", fileDescriptor_696ca1996ae783df) }

var fileDescriptor_696ca1996ae783df = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4f, 0xd4, 0x40,
	0x14, 0xde, 0x02, 0x02, 0x9d, 0xba, 0x44, 0x26, 0x1c, 0x86, 0x8d, 0x96, 0x06, 0x4d, 0x6c, 0x88,
	0xb4, 0x01, 0x0f, 0x1a, 0x6f, 0xbb, 0x59, 0x23, 0x84, 0x98, 0x98, 0x62, 0x38, 0x78, 0x69, 0x86,
	0xce, 0xec, 0x32, 0xa1, 0x9d, 0xa9, 0x9d, 0xd9, 0x0a, 0x47, 0xaf, 0x9e, 0xf8, 0x19, 0x1e, 0x39,
	0xf8, 0x23, 0x38, 0x12, 0x4f, 0x9e, 0xd4, 0xb0, 0x07, 0xfe, 0x86, 0x69, 0x3b, 0x8d, 0xed, 0x26,
	0xc4, 0x78, 0x69, 0xde, 0xfb, 0xde, 0xf7, 0xbd, 0x6f, 0xf2, 0x5e, 0x1f, 0x70, 0x70, 0x94, 0x60,
	0xc6, 0x7d, 0x86, 0x13, 0x3f, 0xdf, 0xf1, 0x09, 0x23, 0x21, 0x11, 0xd1, 0x24, 0xa1, 0x5c, 0x79,
	0x69, 0x26, 0x94, 0x80, 0xdd, 0x8a, 0xe1, 0x31, 0x9c, 0x78, 0xf9, 0x4e, 0x6f, 0xbd, 0x2d, 0xa0,
	0x7c, 0x92, 0xc8, 0x8a, 0xd9, 0x7b, 0xdc, 0x2e, 0xa5, 0x93, 0xe3, 0x98, 0x45, 0xe1, 0x29, 0x3d,
	0x0f, 0x19, 0x1f, 0x09, 0x4d, 0x7a, 0xd2, 0x26, 0x49, 0x9a, 0xe5, 0x2c, 0xa2, 0x21, 0xe5, 0x24,
	0x15, 0xac, 0x36, 0xed, 0x6d, 0xb7, 0x59, 0x39, 0xcd, 0xd8, 0x88, 0x45, 0x58, 0x31, 0xc1, 0xc3,
	0x8c, 0xc6, 0x65, 0x20, 0x4f, 0x58, 0xaa, 0xe9, 0xab, 0x38, 0x61, 0x5c, 0xf8, 0xe5, 0x57, 0x43,
	0xeb, 0x91, 0x90, 0x89, 0x90, 0x61, 0x99, 0xf9, 0x55, 0xa2, 0x4b, 0x6b, 0x63, 0x31, 0x16, 0x15,
	0x5e, 0x44, 0x1a, 0xdd, 0x18, 0x0b, 0x31, 0x8e, 0xa9, 0x5f, 0x66, 0xc7, 0x93, 0x91, 0xaf, 0x58,
	0x42, 0xa5, 0xc2, 0x89, 0x36, 0xd9, 0xfc, 0xbc, 0x08, 0xac, 0xe1, 0xfe, 0x70, 0xa8, 0xc7, 0x03,
	0x57, 0xc0, 0x1c, 0x23, 0xc8, 0x70, 0x0c, 0xd7, 0x0c, 0xe6, 0x18, 0x81, 0x08, 0x2c, 0x45, 0x82,
	0x2b, 0x7a, 0xa6, 0xd0, 0x9c, 0x33, 0xef, 0x9a, 0x41, 0x9d, 0xc2, 0x97, 0x00, 0x14, 0x61, 0x26,
	0xe2, 0x98, 0x66, 0x68, 0xbe, 0x50, 0x0c, 0xd0, 0xf7, 0x6f, 0xdb, 0x6b, 0xfa, 0x59, 0x7d, 0x42,
	0x32, 0x2a, 0xe5, 0xa1, 0xca, 0x18, 0x1f, 0x07, 0x0d, 0x2e, 0xdc, 0x03, 0xd6, 0xdf, 0x31, 0x4a,
	0xb4, 0xe0, 0xcc, 0xbb, 0xd6, 0xee, 0x43, 0xaf, 0xb5, 0x12, 0xef, 0x5d, 0xc9, 0x38, 0xa0, 0xe7,
	0xfb, 0x7c, 0x24, 0x06, 0xe6, 0xd5, 0xcf, 0x8d, 0xce, 0xd7, 0xdb, 0xcb, 0x2d, 0x23, 0x00, 0x69,
	0x5d, 0x91, 0xf0, 0x23, 0xe8, 0xdd, 0x39, 0x45, 0x89, 0xee, 0x95, 0x8d, 0x9f, 0xce, 0x34, 0x3e,
	0x6a, 0x08, 0x82, 0x06, 0xbf, 0xe9, 0xb1, 0x9e, 0xdf, 0x41, 0x92, 0xf0, 0x08, 0xac, 0xce, 0xae,
	0x57, 0xa2, 0xc5, 0xd2, 0xc9, 0x9e, 0x71, 0x3a, 0xac, 0x78, 0xaf, 0x35, 0xad, 0x69, 0xf0, 0x40,
	0xb6, 0x6b, 0x12, 0x6e, 0x82, 0x2e, 0x8e, 0xa5, 0x08, 0x4f, 0xb9, 0xf8, 0xc4, 0x43, 0x2c, 0xd1,
	0x52, 0x39, 0x6e, 0xab, 0x00, 0x0f, 0x0a, 0xac, 0x2f, 0xe1, 0x1e, 0x00, 0x51, 0x46, 0xb1, 0xa2,
	0x24, 0xc4, 0x0a, 0x2d, 0x3b, 0x86, 0x6b, 0xed, 0xf6, 0xbc, 0x6a, 0xc5, 0x5e, 0xbd, 0x62, 0xef,
	0x7d, 0xbd, 0xe2, 0x41, 0xb7, 0x30, 0xbc, 0xf8, 0xb5, 0x61, 0x54, 0xa6, 0xa6, 0x16, 0xf7, 0x55,
	0xd1, 0x69, 0x92, 0x92, 0xba, 0x93, 0xf9, 0xdf, 0x9d, 0xb4, 0xb8, 0xaf, 0xa0, 0x03, 0x2c, 0x42,
	0x71, 0xa4, 0x58, 0x5e, 0x00, 0x08, 0x38, 0x86, 0xbb, 0x1c, 0x34, 0x21, 0xf8, 0x06, 0xac, 0x34,
	0xd2, 0xc2, 0xcf, 0xfa, 0xa7, 0xdf, 0x42, 0xe1, 0x15, 0x74, 0x1b, 0xba, 0xbe, 0x82, 0x2f, 0x00,
	0x28, 0x4e, 0x39, 0xa1, 0xea, 0x44, 0x10, 0x74, 0xdf, 0x31, 0xdc, 0x95, 0x5d, 0x34, 0x33, 0xf3,
	0xe1, 0xfe, 0xf0, 0x6d, 0x59, 0x0f, 0x4c, 0xc2, 0x48, 0x15, 0xbe, 0x7a, 0xf4, 0xe5, 0xf6, 0x72,
	0x0b, 0xe9, 0xeb, 0x3b, 0x2b, 0xef, 0xaf, 0xf1, 0xcf, 0x0f, 0x9e, 0x5d, 0xdd, 0xd8, 0xc6, 0xf5,
	0x8d, 0x6d, 0xfc, 0xbe, 0xb1, 0x8d, 0x8b, 0xa9, 0xdd, 0xb9, 0x9e, 0xda, 0x9d, 0x1f, 0x53, 0xbb,
	0xf3, 0x01, 0xb6, 0x34, 0xea, 0x3c, 0xa5, 0xf2, 0x78, 0xb1, 0x7c, 0xee, 0xf3, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd1, 0x4c, 0xd8, 0xba, 0x65, 0x04, 0x00, 0x00,
}

func (m *DIDDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DIDDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DIDDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DidMethod != 0 {
		i = encodeVarintDidDocument(dAtA, i, uint64(m.DidMethod))
		i--
		dAtA[i] = 0x60
	}
	if m.DeactivatedAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.DeactivatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.DeactivatedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintDidDocument(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x5a
	}
	if m.Deactivated {
		i--
		if m.Deactivated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintDidDocument(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x4a
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintDidDocument(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x42
	if len(m.AlsoKnownAs) > 0 {
		for iNdEx := len(m.AlsoKnownAs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AlsoKnownAs[iNdEx])
			copy(dAtA[i:], m.AlsoKnownAs[iNdEx])
			i = encodeVarintDidDocument(dAtA, i, uint64(len(m.AlsoKnownAs[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ServiceEndpoints) > 0 {
		for iNdEx := len(m.ServiceEndpoints) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ServiceEndpoints[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.VerificationRelationships) > 0 {
		for iNdEx := len(m.VerificationRelationships) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VerificationRelationships[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.PublicKeys) > 0 {
		for iNdEx := len(m.PublicKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PublicKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDidDocument(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Controller) > 0 {
		i -= len(m.Controller)
		copy(dAtA[i:], m.Controller)
		i = encodeVarintDidDocument(dAtA, i, uint64(len(m.Controller)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Context) > 0 {
		for iNdEx := len(m.Context) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Context[iNdEx])
			copy(dAtA[i:], m.Context[iNdEx])
			i = encodeVarintDidDocument(dAtA, i, uint64(len(m.Context[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDidDocument(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDidDocument(dAtA []byte, offset int, v uint64) int {
	offset -= sovDidDocument(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DIDDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDidDocument(uint64(l))
	}
	if len(m.Context) > 0 {
		for _, s := range m.Context {
			l = len(s)
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	l = len(m.Controller)
	if l > 0 {
		n += 1 + l + sovDidDocument(uint64(l))
	}
	if len(m.PublicKeys) > 0 {
		for _, e := range m.PublicKeys {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.VerificationRelationships) > 0 {
		for _, e := range m.VerificationRelationships {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.ServiceEndpoints) > 0 {
		for _, e := range m.ServiceEndpoints {
			l = e.Size()
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	if len(m.AlsoKnownAs) > 0 {
		for _, s := range m.AlsoKnownAs {
			l = len(s)
			n += 1 + l + sovDidDocument(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovDidDocument(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovDidDocument(uint64(l))
	if m.Deactivated {
		n += 2
	}
	if m.DeactivatedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.DeactivatedAt)
		n += 1 + l + sovDidDocument(uint64(l))
	}
	if m.DidMethod != 0 {
		n += 1 + sovDidDocument(uint64(m.DidMethod))
	}
	return n
}

func sovDidDocument(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDidDocument(x uint64) (n int) {
	return sovDidDocument(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DIDDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDidDocument
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DIDDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DIDDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = append(m.Context, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Controller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeys = append(m.PublicKeys, PublicKeyInfo{})
			if err := m.PublicKeys[len(m.PublicKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationRelationships", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationRelationships = append(m.VerificationRelationships, VerificationRelationship{})
			if err := m.VerificationRelationships[len(m.VerificationRelationships)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceEndpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceEndpoints = append(m.ServiceEndpoints, ServiceEndpoint{})
			if err := m.ServiceEndpoints[len(m.ServiceEndpoints)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlsoKnownAs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlsoKnownAs = append(m.AlsoKnownAs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deactivated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Deactivated = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeactivatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDidDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDidDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DeactivatedAt == nil {
				m.DeactivatedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.DeactivatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidMethod", wireType)
			}
			m.DidMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DidMethod |= DIDMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDidDocument(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDidDocument
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDidDocument(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDidDocument
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDidDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDidDocument
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDidDocument
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDidDocument
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDidDocument        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDidDocument          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDidDocument = fmt.Errorf("proto: unexpected end of group")
)
