// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the identity module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// did_documents contains all DID documents
	DidDocuments []DIDDocument `protobuf:"bytes,2,rep,name=did_documents,json=didDocuments,proto3" json:"did_documents"`
	// credentials contains all verifiable credentials
	Credentials []VerifiableCredential `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials"`
	// revoked_credential_ids contains IDs of revoked credentials
	RevokedCredentialIds []string `protobuf:"bytes,4,rep,name=revoked_credential_ids,json=revokedCredentialIds,proto3" json:"revoked_credential_ids,omitempty"`
	// device_keys contains all registered device keys
	DeviceKeys []DeviceKey `protobuf:"bytes,5,rep,name=device_keys,json=deviceKeys,proto3" json:"device_keys"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_379c73af8ecffd94, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDidDocuments() []DIDDocument {
	if m != nil {
		return m.DidDocuments
	}
	return nil
}

func (m *GenesisState) GetCredentials() []VerifiableCredential {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *GenesisState) GetRevokedCredentialIds() []string {
	if m != nil {
		return m.RevokedCredentialIds
	}
	return nil
}

func (m *GenesisState) GetDeviceKeys() []DeviceKey {
	if m != nil {
		return m.DeviceKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "acmain.iam.v1.GenesisState")
}

func init() { proto.RegisterFile("acmain/iam/v1/genesis.proto", fileDescriptor_379c73af8ecffd94) }

var fileDescriptor_379c73af8ecffd94 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x93, 0xb6, 0x16, 0x3a, 0x69, 0x17, 0x86, 0x2a, 0x21, 0x42, 0x0c, 0xba, 0xa9, 0x22,
	0x09, 0xad, 0x2e, 0xdc, 0x09, 0xb5, 0x22, 0xa5, 0x1b, 0xa9, 0xe0, 0xc2, 0x4d, 0x98, 0x66, 0xae,
	0x65, 0x68, 0x93, 0x29, 0x99, 0x18, 0xec, 0x5b, 0xf8, 0x18, 0x2e, 0x7d, 0x8c, 0x2e, 0x0b, 0x6e,
	0x5c, 0x89, 0xb4, 0x0b, 0x5f, 0x43, 0x3a, 0x99, 0xfe, 0x24, 0x9b, 0x70, 0xb9, 0xe7, 0xcb, 0xb9,
	0x39, 0x39, 0xe8, 0x08, 0xfb, 0x01, 0xa6, 0xa1, 0x4b, 0x71, 0xe0, 0x26, 0x4d, 0x77, 0x08, 0x21,
	0x70, 0xca, 0x9d, 0x49, 0xc4, 0x62, 0xa6, 0xd7, 0x52, 0xd1, 0xa1, 0x38, 0x70, 0x92, 0xa6, 0x69,
	0x65, 0x59, 0x02, 0x09, 0xf5, 0xc1, 0x1b, 0xc1, 0x34, 0xc5, 0x4d, 0x3b, 0xa7, 0x53, 0xe2, 0x11,
	0xe6, 0xbf, 0x06, 0x10, 0xc6, 0x92, 0x30, 0xb3, 0xc4, 0x04, 0x47, 0x38, 0x90, 0xc7, 0xcc, 0xb3,
	0xac, 0x96, 0x40, 0x44, 0x5f, 0x28, 0x1e, 0x8c, 0xc1, 0xf3, 0x23, 0x20, 0x10, 0xc6, 0x14, 0x8f,
	0x25, 0xba, 0x8f, 0x03, 0x1a, 0x32, 0x57, 0x3c, 0xe5, 0xaa, 0x3e, 0x64, 0x43, 0x26, 0x46, 0x77,
	0x35, 0xa5, 0xdb, 0x93, 0xaf, 0x02, 0xaa, 0xde, 0xa7, 0x91, 0x1e, 0x63, 0x1c, 0x83, 0x7e, 0x8d,
	0xca, 0xe9, 0x51, 0x43, 0xb5, 0xd5, 0x86, 0xd6, 0x3a, 0x70, 0x32, 0x11, 0x9d, 0x07, 0x21, 0xb6,
	0x2b, 0xb3, 0x9f, 0x63, 0xe5, 0xe3, 0xef, 0xf3, 0x5c, 0xed, 0x4b, 0x5e, 0xbf, 0x43, 0xb5, 0xdd,
	0x40, 0xdc, 0x28, 0xd8, 0xc5, 0x86, 0xd6, 0x32, 0x73, 0x06, 0x9d, 0x6e, 0xa7, 0x23, 0x91, 0x76,
	0x69, 0xe5, 0xd2, 0xaf, 0x12, 0x4a, 0xd6, 0x2b, 0xae, 0xf7, 0x90, 0xb6, 0x8d, 0xc3, 0x8d, 0xa2,
	0x30, 0x39, 0xcd, 0x99, 0x3c, 0x6d, 0xb2, 0xdf, 0x6e, 0x58, 0xe9, 0xb6, 0xfb, 0xb6, 0x7e, 0x85,
	0x0e, 0x23, 0x48, 0xd8, 0x08, 0xc8, 0xce, 0x3f, 0xf2, 0x28, 0xe1, 0x46, 0xc9, 0x2e, 0x36, 0x2a,
	0xfd, 0xba, 0x54, 0xb7, 0x2e, 0x5d, 0xc2, 0xf5, 0x1b, 0xa4, 0x6d, 0xab, 0xe3, 0xc6, 0x9e, 0xf8,
	0x04, 0x23, 0x9f, 0x43, 0x10, 0x3d, 0x98, 0xca, 0xbb, 0x88, 0xac, 0x17, 0xbc, 0x7d, 0x31, 0x5b,
	0x58, 0xea, 0x7c, 0x61, 0xa9, 0xbf, 0x0b, 0x4b, 0x7d, 0x5f, 0x5a, 0xca, 0x7c, 0x69, 0x29, 0xdf,
	0x4b, 0x4b, 0x79, 0xd6, 0x65, 0x87, 0x6f, 0xa2, 0xc5, 0x78, 0x3a, 0x01, 0x3e, 0x28, 0x8b, 0x2a,
	0x2e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x2e, 0xbe, 0x30, 0x6a, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeviceKeys) > 0 {
		for iNdEx := len(m.DeviceKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DeviceKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RevokedCredentialIds) > 0 {
		for iNdEx := len(m.RevokedCredentialIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RevokedCredentialIds[iNdEx])
			copy(dAtA[i:], m.RevokedCredentialIds[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RevokedCredentialIds[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Credentials) > 0 {
		for iNdEx := len(m.Credentials) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Credentials[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.DidDocuments) > 0 {
		for iNdEx := len(m.DidDocuments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DidDocuments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.DidDocuments) > 0 {
		for _, e := range m.DidDocuments {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Credentials) > 0 {
		for _, e := range m.Credentials {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RevokedCredentialIds) > 0 {
		for _, s := range m.RevokedCredentialIds {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DeviceKeys) > 0 {
		for _, e := range m.DeviceKeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocuments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DidDocuments = append(m.DidDocuments, DIDDocument{})
			if err := m.DidDocuments[len(m.DidDocuments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credentials", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credentials = append(m.Credentials, VerifiableCredential{})
			if err := m.Credentials[len(m.Credentials)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedCredentialIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevokedCredentialIds = append(m.RevokedCredentialIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceKeys = append(m.DeviceKeys, DeviceKey{})
			if err := m.DeviceKeys[len(m.DeviceKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
