// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/public_key_info.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PublicKeyInfo defines the PublicKeyInfo message.
type PublicKeyInfo struct {
	// key_id is a unique identifier for the key within the DID document
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// public_key is the raw public key bytes
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// key_type specifies the cryptographic algorithm
	KeyType KeyType `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=acmain.iam.v1.KeyType" json:"key_type,omitempty"`
	// purpose describes the key's purpose (e.g., "authentication", "assertionMethod")
	Purpose string `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// controller is the DID that controls this key (can differ from subject)
	Controller string `protobuf:"bytes,5,opt,name=controller,proto3" json:"controller,omitempty"`
	// created_at is the block timestamp when the key was added
	CreatedAt time.Time `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// revoked_at is the block timestamp when the key was revoked (null if active)
	RevokedAt *time.Time `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3,stdtime" json:"revoked_at,omitempty"`
}

func (m *PublicKeyInfo) Reset()         { *m = PublicKeyInfo{} }
func (m *PublicKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PublicKeyInfo) ProtoMessage()    {}
func (*PublicKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8da89e4f940a83d7, []int{0}
}
func (m *PublicKeyInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PublicKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PublicKeyInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PublicKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyInfo.Merge(m, src)
}
func (m *PublicKeyInfo) XXX_Size() int {
	return m.Size()
}
func (m *PublicKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyInfo proto.InternalMessageInfo

func (m *PublicKeyInfo) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

func (m *PublicKeyInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PublicKeyInfo) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KEY_TYPE_UNSPECIFIED
}

func (m *PublicKeyInfo) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *PublicKeyInfo) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *PublicKeyInfo) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *PublicKeyInfo) GetRevokedAt() *time.Time {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicKeyInfo)(nil), "acmain.iam.v1.PublicKeyInfo")
}

func init() {
	proto.RegisterFile("acmain/iam/v1/public_key_info.proto", fileDescriptor_8da89e4f940a83d7)
}

var fileDescriptor_8da89e4f940a83d7 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xbd, 0x8e, 0xd3, 0x40,
	0x10, 0xc7, 0xbd, 0x21, 0x1f, 0x78, 0x21, 0x48, 0xac, 0x00, 0x19, 0x4b, 0xd8, 0x16, 0x34, 0x56,
	0x84, 0xd6, 0x4a, 0xe8, 0x68, 0x50, 0x52, 0x11, 0xa5, 0x41, 0x56, 0x2a, 0x9a, 0x68, 0xe3, 0x6c,
	0x2c, 0xcb, 0x1f, 0xbb, 0xb2, 0xd7, 0x11, 0x7e, 0x05, 0xaa, 0x3c, 0x06, 0x65, 0x1e, 0x23, 0x65,
	0x4a, 0xaa, 0xdc, 0x29, 0x29, 0xf2, 0x1a, 0x27, 0xaf, 0x6d, 0xdd, 0xb9, 0xba, 0x66, 0x35, 0x33,
	0x3b, 0xbf, 0x99, 0xf9, 0xcf, 0xc0, 0x2f, 0xc4, 0x8b, 0x49, 0x90, 0x38, 0x01, 0x89, 0x9d, 0xdd,
	0xd8, 0xe1, 0xf9, 0x3a, 0x0a, 0xbc, 0x55, 0x48, 0x8b, 0x55, 0x90, 0x6c, 0x19, 0xe6, 0x29, 0x13,
	0x0c, 0x0d, 0xab, 0x24, 0x1c, 0x90, 0x18, 0xef, 0xc6, 0xfa, 0xc7, 0x36, 0x43, 0x93, 0x3c, 0xce,
	0xaa, 0x4c, 0xfd, 0x2d, 0x89, 0x83, 0x84, 0x39, 0xf2, 0xad, 0x43, 0xef, 0x7c, 0xe6, 0x33, 0x69,
	0x3a, 0xa5, 0x55, 0x47, 0x4d, 0x9f, 0x31, 0x3f, 0xa2, 0x8e, 0xf4, 0xd6, 0xf9, 0xd6, 0x11, 0x41,
	0x4c, 0x33, 0x41, 0x62, 0x5e, 0x25, 0x7c, 0x3e, 0x77, 0xe0, 0xf0, 0x97, 0x9c, 0x66, 0x41, 0x8b,
	0x79, 0xb2, 0x65, 0xe8, 0x3d, 0xec, 0xcb, 0xb9, 0x36, 0x1a, 0xb0, 0x80, 0xad, 0xba, 0xbd, 0x90,
	0x16, 0xf3, 0x0d, 0xfa, 0x04, 0xe1, 0xe3, 0xd4, 0x5a, 0xc7, 0x02, 0xf6, 0x6b, 0x57, 0xe5, 0x0d,
	0x89, 0xc6, 0xf0, 0x65, 0x49, 0x89, 0x82, 0x53, 0xed, 0x85, 0x05, 0xec, 0x37, 0x93, 0x0f, 0xb8,
	0x25, 0x07, 0x2f, 0x68, 0xb1, 0x2c, 0x38, 0x75, 0x07, 0x61, 0x65, 0x20, 0x0d, 0x0e, 0x78, 0x9e,
	0x72, 0x96, 0x51, 0xad, 0x2b, 0x3b, 0x35, 0x2e, 0x32, 0x20, 0xf4, 0x58, 0x22, 0x52, 0x16, 0x45,
	0x34, 0xd5, 0x7a, 0xf2, 0xf3, 0x49, 0x04, 0xfd, 0x84, 0xd0, 0x4b, 0x29, 0x11, 0x74, 0xb3, 0x22,
	0x42, 0xeb, 0x5b, 0xc0, 0x7e, 0x35, 0xd1, 0x71, 0x25, 0x15, 0x37, 0x52, 0xf1, 0xb2, 0x91, 0x3a,
	0x1b, 0x1e, 0xcf, 0xa6, 0xb2, 0xbf, 0x33, 0xc1, 0xbf, 0xdb, 0x61, 0x04, 0x5c, 0xb5, 0x86, 0xa7,
	0x02, 0xfd, 0x80, 0x30, 0xa5, 0x3b, 0x16, 0x56, 0x95, 0x06, 0xcf, 0x56, 0xea, 0x96, 0x55, 0x5c,
	0xb5, 0x66, 0xa6, 0xe2, 0xbb, 0xf9, 0xf7, 0x76, 0x18, 0xe9, 0xf5, 0xa5, 0xfe, 0xc8, 0x5b, 0xb5,
	0xd6, 0x39, 0xfb, 0x7a, 0xbc, 0x18, 0xe0, 0x74, 0x31, 0xc0, 0xfd, 0xc5, 0x00, 0xfb, 0xab, 0xa1,
	0x9c, 0xae, 0x86, 0xf2, 0xff, 0x6a, 0x28, 0xbf, 0x51, 0x8b, 0x2a, 0x37, 0x97, 0xad, 0xfb, 0xb2,
	0xe7, 0xb7, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x4a, 0xc3, 0x2a, 0x30, 0x02, 0x00, 0x00,
}

func (m *PublicKeyInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PublicKeyInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PublicKeyInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevokedAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RevokedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x3a
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintPublicKeyInfo(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x32
	if len(m.Controller) > 0 {
		i -= len(m.Controller)
		copy(dAtA[i:], m.Controller)
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(len(m.Controller)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Purpose) > 0 {
		i -= len(m.Purpose)
		copy(dAtA[i:], m.Purpose)
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(len(m.Purpose)))
		i--
		dAtA[i] = 0x22
	}
	if m.KeyType != 0 {
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(m.KeyType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeyId) > 0 {
		i -= len(m.KeyId)
		copy(dAtA[i:], m.KeyId)
		i = encodeVarintPublicKeyInfo(dAtA, i, uint64(len(m.KeyId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPublicKeyInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovPublicKeyInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PublicKeyInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.KeyId)
	if l > 0 {
		n += 1 + l + sovPublicKeyInfo(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovPublicKeyInfo(uint64(l))
	}
	if m.KeyType != 0 {
		n += 1 + sovPublicKeyInfo(uint64(m.KeyType))
	}
	l = len(m.Purpose)
	if l > 0 {
		n += 1 + l + sovPublicKeyInfo(uint64(l))
	}
	l = len(m.Controller)
	if l > 0 {
		n += 1 + l + sovPublicKeyInfo(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovPublicKeyInfo(uint64(l))
	if m.RevokedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt)
		n += 1 + l + sovPublicKeyInfo(uint64(l))
	}
	return n
}

func sovPublicKeyInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPublicKeyInfo(x uint64) (n int) {
	return sovPublicKeyInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PublicKeyInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPublicKeyInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PublicKeyInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PublicKeyInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			m.KeyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyType |= KeyType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Purpose", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Purpose = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Controller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Controller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RevokedAt == nil {
				m.RevokedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RevokedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPublicKeyInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPublicKeyInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPublicKeyInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPublicKeyInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPublicKeyInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPublicKeyInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPublicKeyInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPublicKeyInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPublicKeyInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPublicKeyInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPublicKeyInfo = fmt.Errorf("proto: unexpected end of group")
)
