// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/iam/v1/verifiable_credential.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VerifiableCredential represents a W3C Verifiable Credential
type VerifiableCredential struct {
	// id is the unique identifier for this credential
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// context defines the JSON-LD context
	Context []string `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	// type specifies credential types (always includes "VerifiableCredential")
	Type []string `protobuf:"bytes,3,rep,name=type,proto3" json:"type,omitempty"`
	// issuer is the address/DID that issued this credential
	Issuer string `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// issued_at is the block timestamp when credential was issued
	IssuedAt time.Time `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3,stdtime" json:"issued_at"`
	// credential_subject is the subject and their claims
	CredentialSubject CredentialSubject `protobuf:"bytes,6,opt,name=credential_subject,json=credentialSubject,proto3" json:"credential_subject"`
	// valid_from is the earliest time the credential is valid
	ValidFrom *time.Time `protobuf:"bytes,7,opt,name=valid_from,json=validFrom,proto3,stdtime" json:"valid_from,omitempty"`
	// valid_until is the expiration time of the credential
	ValidUntil *time.Time `protobuf:"bytes,8,opt,name=valid_until,json=validUntil,proto3,stdtime" json:"valid_until,omitempty"`
	// credential_status tracks revocation/suspension
	CredentialStatus *CredentialStatusInfo `protobuf:"bytes,9,opt,name=credential_status,json=credentialStatus,proto3" json:"credential_status,omitempty"`
	// proof is the cryptographic proof of the credential
	Proof CredentialProof `protobuf:"bytes,10,opt,name=proof,proto3" json:"proof"`
	// credential_type is the semantic type of the credential
	CredentialType CredentialType `protobuf:"varint,11,opt,name=credential_type,json=credentialType,proto3,enum=acmain.iam.v1.CredentialType" json:"credential_type,omitempty"`
	// holder is the DID of the entity that holds this credential
	Holder string `protobuf:"bytes,12,opt,name=holder,proto3" json:"holder,omitempty"`
	// metadata stores additional issuer-specific attributes
	Metadata map[string]string `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// refresh_service enables credential renewal
	RefreshService string `protobuf:"bytes,14,opt,name=refresh_service,json=refreshService,proto3" json:"refresh_service,omitempty"`
}

func (m *VerifiableCredential) Reset()         { *m = VerifiableCredential{} }
func (m *VerifiableCredential) String() string { return proto.CompactTextString(m) }
func (*VerifiableCredential) ProtoMessage()    {}
func (*VerifiableCredential) Descriptor() ([]byte, []int) {
	return fileDescriptor_b77ffda27a2221ac, []int{0}
}
func (m *VerifiableCredential) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifiableCredential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifiableCredential.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifiableCredential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiableCredential.Merge(m, src)
}
func (m *VerifiableCredential) XXX_Size() int {
	return m.Size()
}
func (m *VerifiableCredential) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiableCredential.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiableCredential proto.InternalMessageInfo

func (m *VerifiableCredential) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VerifiableCredential) GetContext() []string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *VerifiableCredential) GetType() []string {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *VerifiableCredential) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *VerifiableCredential) GetIssuedAt() time.Time {
	if m != nil {
		return m.IssuedAt
	}
	return time.Time{}
}

func (m *VerifiableCredential) GetCredentialSubject() CredentialSubject {
	if m != nil {
		return m.CredentialSubject
	}
	return CredentialSubject{}
}

func (m *VerifiableCredential) GetValidFrom() *time.Time {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *VerifiableCredential) GetValidUntil() *time.Time {
	if m != nil {
		return m.ValidUntil
	}
	return nil
}

func (m *VerifiableCredential) GetCredentialStatus() *CredentialStatusInfo {
	if m != nil {
		return m.CredentialStatus
	}
	return nil
}

func (m *VerifiableCredential) GetProof() CredentialProof {
	if m != nil {
		return m.Proof
	}
	return CredentialProof{}
}

func (m *VerifiableCredential) GetCredentialType() CredentialType {
	if m != nil {
		return m.CredentialType
	}
	return CREDENTIAL_TYPE_UNSPECIFIED
}

func (m *VerifiableCredential) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *VerifiableCredential) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VerifiableCredential) GetRefreshService() string {
	if m != nil {
		return m.RefreshService
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifiableCredential)(nil), "acmain.iam.v1.VerifiableCredential")
	proto.RegisterMapType((map[string]string)(nil), "acmain.iam.v1.VerifiableCredential.MetadataEntry")
}

func init() {
	proto.RegisterFile("acmain/iam/v1/verifiable_credential.proto", fileDescriptor_b77ffda27a2221ac)
}

var fileDescriptor_b77ffda27a2221ac = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0x6e, 0xda, 0xad, 0x5b, 0xdd, 0x5f, 0xbb, 0xcd, 0xaa, 0x7e, 0x32, 0x95, 0xc8, 0x02, 0x48,
	0x50, 0x26, 0x48, 0xd8, 0xb8, 0xa0, 0x71, 0x98, 0x56, 0xc4, 0x24, 0x0e, 0x93, 0xa6, 0x6c, 0x70,
	0xd8, 0x25, 0x72, 0x13, 0xa7, 0x33, 0x24, 0x71, 0x65, 0x3b, 0xd1, 0xfa, 0x15, 0x38, 0xed, 0x63,
	0x70, 0xdc, 0x81, 0x0f, 0xb1, 0xe3, 0xc4, 0x89, 0x13, 0xa0, 0xed, 0xb0, 0x6f, 0x81, 0x50, 0xec,
	0x74, 0x5b, 0xaa, 0x55, 0x70, 0x89, 0xde, 0x3f, 0xcf, 0xf3, 0xf8, 0x79, 0x9d, 0xd7, 0xe0, 0x29,
	0xf6, 0x63, 0x4c, 0x13, 0x87, 0xe2, 0xd8, 0xc9, 0xd6, 0x9d, 0x8c, 0x70, 0x1a, 0x52, 0x3c, 0x88,
	0x88, 0xe7, 0x73, 0x12, 0x90, 0x44, 0x52, 0x1c, 0xd9, 0x23, 0xce, 0x24, 0x83, 0x2d, 0x0d, 0xb5,
	0x29, 0x8e, 0xed, 0x6c, 0xbd, 0x6b, 0x96, 0x99, 0xd3, 0xf0, 0xee, 0xbd, 0x72, 0x9f, 0x24, 0x69,
	0x2c, 0x8a, 0xd6, 0x0a, 0x8e, 0x69, 0xc2, 0x1c, 0xf5, 0x9d, 0xa0, 0x7d, 0x26, 0x62, 0x26, 0x3c,
	0x95, 0x39, 0x3a, 0x29, 0x5a, 0x9d, 0x21, 0x1b, 0x32, 0x5d, 0xcf, 0xa3, 0xa2, 0xba, 0x3a, 0x64,
	0x6c, 0x18, 0x11, 0x47, 0x65, 0x83, 0x34, 0x74, 0x24, 0x8d, 0x89, 0x90, 0x38, 0x1e, 0x69, 0xc0,
	0xc3, 0xdf, 0x75, 0xd0, 0xf9, 0x70, 0x3d, 0xce, 0x9b, 0x6b, 0x7b, 0xb0, 0x0d, 0xaa, 0x34, 0x40,
	0x86, 0x65, 0xf4, 0x1a, 0x6e, 0x95, 0x06, 0x10, 0x81, 0x05, 0x9f, 0x25, 0x92, 0x1c, 0x4b, 0x54,
	0xb5, 0x6a, 0xbd, 0x86, 0x3b, 0x49, 0x21, 0x04, 0x73, 0x72, 0x3c, 0x22, 0xa8, 0xa6, 0xca, 0x2a,
	0x86, 0x2f, 0x40, 0x9d, 0x0a, 0x91, 0x12, 0x8e, 0xe6, 0x72, 0x85, 0x3e, 0xfa, 0xf6, 0xf5, 0x79,
	0xa7, 0xf0, 0xbb, 0x1d, 0x04, 0x9c, 0x08, 0xb1, 0x2f, 0x39, 0x4d, 0x86, 0x6e, 0x81, 0x83, 0x3b,
	0xa0, 0xa1, 0xa2, 0xc0, 0xc3, 0x12, 0xcd, 0x5b, 0x46, 0xaf, 0xb9, 0xd1, 0xb5, 0xb5, 0x7b, 0x7b,
	0xe2, 0xde, 0x3e, 0x98, 0xb8, 0xef, 0xb7, 0xce, 0x7e, 0xac, 0x56, 0x4e, 0x7e, 0xae, 0x1a, 0x5f,
	0xae, 0x4e, 0xd7, 0x0c, 0x77, 0x51, 0x73, 0xb7, 0x25, 0x3c, 0x04, 0xf0, 0xe6, 0x92, 0x3d, 0x91,
	0x0e, 0x3e, 0x12, 0x5f, 0xa2, 0xba, 0x12, 0xb4, 0xec, 0xd2, 0xcf, 0xb1, 0x6f, 0xc6, 0xdd, 0xd7,
	0xb8, 0x7e, 0x23, 0x97, 0xd5, 0x92, 0x2b, 0xfe, 0x74, 0x17, 0x6e, 0x01, 0x90, 0xe1, 0x88, 0x06,
	0x5e, 0xc8, 0x59, 0x8c, 0x16, 0xfe, 0x6a, 0x72, 0x2e, 0x37, 0xe8, 0x36, 0x14, 0x67, 0x87, 0xb3,
	0x18, 0x6e, 0x83, 0xa6, 0x16, 0x48, 0x13, 0x49, 0x23, 0xb4, 0xf8, 0x8f, 0x0a, 0xfa, 0xd4, 0xf7,
	0x39, 0x07, 0xee, 0x81, 0x95, 0xdb, 0xf3, 0x49, 0x2c, 0x53, 0x81, 0x1a, 0x4a, 0xe8, 0xd1, 0xec,
	0xf1, 0x14, 0xec, 0x5d, 0x12, 0x32, 0x77, 0xd9, 0x9f, 0xaa, 0xc2, 0x2d, 0x30, 0x3f, 0xe2, 0x8c,
	0x85, 0x08, 0x28, 0x15, 0x73, 0xa6, 0xca, 0x5e, 0x8e, 0xba, 0x7d, 0x45, 0x9a, 0x07, 0x77, 0xc0,
	0xd2, 0x2d, 0x4b, 0x6a, 0x17, 0x9a, 0x96, 0xd1, 0x6b, 0x6f, 0xdc, 0x9f, 0x29, 0x75, 0x30, 0x1e,
	0x11, 0xb7, 0xed, 0x97, 0x72, 0xf8, 0x3f, 0xa8, 0x1f, 0xb1, 0x28, 0x20, 0x1c, 0xfd, 0xa7, 0xd6,
	0xae, 0xc8, 0xe0, 0x2e, 0x58, 0x8c, 0x89, 0xc4, 0x01, 0x96, 0x18, 0xb5, 0xac, 0x5a, 0xaf, 0xb9,
	0xb1, 0x3e, 0x25, 0x7c, 0xd7, 0x06, 0xdb, 0xbb, 0x05, 0xe7, 0x6d, 0x22, 0xf9, 0xd8, 0xbd, 0x96,
	0x80, 0x4f, 0xc0, 0x12, 0x27, 0x21, 0x27, 0xe2, 0xc8, 0x13, 0x84, 0x67, 0xd4, 0x27, 0xa8, 0xad,
	0xce, 0x6b, 0x17, 0xe5, 0x7d, 0x5d, 0xed, 0xbe, 0x06, 0xad, 0x92, 0x06, 0x5c, 0x06, 0xb5, 0x4f,
	0x64, 0x5c, 0x3c, 0x8a, 0x3c, 0x84, 0x1d, 0x30, 0x9f, 0xe1, 0x28, 0x25, 0xa8, 0xaa, 0x6a, 0x3a,
	0xd9, 0xac, 0xbe, 0x32, 0x36, 0x1f, 0x7f, 0xbe, 0x3a, 0x5d, 0x7b, 0x50, 0xbc, 0xee, 0x63, 0xf5,
	0xbe, 0xef, 0x72, 0xd9, 0x7f, 0x76, 0x76, 0x61, 0x1a, 0xe7, 0x17, 0xa6, 0xf1, 0xeb, 0xc2, 0x34,
	0x4e, 0x2e, 0xcd, 0xca, 0xf9, 0xa5, 0x59, 0xf9, 0x7e, 0x69, 0x56, 0x0e, 0x61, 0x89, 0x9c, 0x5f,
	0xab, 0x18, 0xd4, 0xd5, 0x8e, 0xbc, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x66, 0xcf, 0x69, 0xce,
	0x91, 0x04, 0x00, 0x00,
}

func (m *VerifiableCredential) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifiableCredential) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerifiableCredential) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RefreshService) > 0 {
		i -= len(m.RefreshService)
		copy(dAtA[i:], m.RefreshService)
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.RefreshService)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0x62
	}
	if m.CredentialType != 0 {
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(m.CredentialType))
		i--
		dAtA[i] = 0x58
	}
	{
		size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.CredentialStatus != nil {
		{
			size, err := m.CredentialStatus.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.ValidUntil != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ValidUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ValidUntil):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x42
	}
	if m.ValidFrom != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ValidFrom, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ValidFrom):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.CredentialSubject.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.IssuedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.IssuedAt):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintVerifiableCredential(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x2a
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Type) > 0 {
		for iNdEx := len(m.Type) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Type[iNdEx])
			copy(dAtA[i:], m.Type[iNdEx])
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.Type[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Context) > 0 {
		for iNdEx := len(m.Context) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Context[iNdEx])
			copy(dAtA[i:], m.Context[iNdEx])
			i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.Context[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintVerifiableCredential(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerifiableCredential(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerifiableCredential(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VerifiableCredential) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	if len(m.Context) > 0 {
		for _, s := range m.Context {
			l = len(s)
			n += 1 + l + sovVerifiableCredential(uint64(l))
		}
	}
	if len(m.Type) > 0 {
		for _, s := range m.Type {
			l = len(s)
			n += 1 + l + sovVerifiableCredential(uint64(l))
		}
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.IssuedAt)
	n += 1 + l + sovVerifiableCredential(uint64(l))
	l = m.CredentialSubject.Size()
	n += 1 + l + sovVerifiableCredential(uint64(l))
	if m.ValidFrom != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ValidFrom)
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	if m.ValidUntil != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ValidUntil)
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	if m.CredentialStatus != nil {
		l = m.CredentialStatus.Size()
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	l = m.Proof.Size()
	n += 1 + l + sovVerifiableCredential(uint64(l))
	if m.CredentialType != 0 {
		n += 1 + sovVerifiableCredential(uint64(m.CredentialType))
	}
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovVerifiableCredential(uint64(len(k))) + 1 + len(v) + sovVerifiableCredential(uint64(len(v)))
			n += mapEntrySize + 1 + sovVerifiableCredential(uint64(mapEntrySize))
		}
	}
	l = len(m.RefreshService)
	if l > 0 {
		n += 1 + l + sovVerifiableCredential(uint64(l))
	}
	return n
}

func sovVerifiableCredential(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerifiableCredential(x uint64) (n int) {
	return sovVerifiableCredential(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VerifiableCredential) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerifiableCredential
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifiableCredential: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifiableCredential: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = append(m.Context, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = append(m.Type, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.IssuedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSubject", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CredentialSubject.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFrom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidFrom == nil {
				m.ValidFrom = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ValidFrom, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidUntil == nil {
				m.ValidUntil = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ValidUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialStatus", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CredentialStatus == nil {
				m.CredentialStatus = &CredentialStatusInfo{}
			}
			if err := m.CredentialStatus.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialType", wireType)
			}
			m.CredentialType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialType |= CredentialType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowVerifiableCredential
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowVerifiableCredential
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthVerifiableCredential
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthVerifiableCredential
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowVerifiableCredential
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthVerifiableCredential
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthVerifiableCredential
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipVerifiableCredential(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthVerifiableCredential
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefreshService", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefreshService = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVerifiableCredential(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerifiableCredential
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerifiableCredential(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerifiableCredential
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerifiableCredential
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerifiableCredential
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerifiableCredential
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerifiableCredential
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerifiableCredential        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerifiableCredential          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerifiableCredential = fmt.Errorf("proto: unexpected end of group")
)
