// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: acmain/permission/v1/permission.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConditionType defines the type of permission condition
type ConditionType int32

const (
	ConditionType_CONDITION_TYPE_UNSPECIFIED     ConditionType = 0
	ConditionType_CONDITION_TYPE_TIME_WINDOW     ConditionType = 1
	ConditionType_CONDITION_TYPE_LOCATION        ConditionType = 2
	ConditionType_CONDITION_TYPE_IP_RANGE        ConditionType = 3
	ConditionType_CONDITION_TYPE_CREDENTIAL_TYPE ConditionType = 4
	ConditionType_CONDITION_TYPE_MFA             ConditionType = 5
	ConditionType_CONDITION_TYPE_DEVICE_TYPE     ConditionType = 6
)

var ConditionType_name = map[int32]string{
	0: "CONDITION_TYPE_UNSPECIFIED",
	1: "CONDITION_TYPE_TIME_WINDOW",
	2: "CONDITION_TYPE_LOCATION",
	3: "CONDITION_TYPE_IP_RANGE",
	4: "CONDITION_TYPE_CREDENTIAL_TYPE",
	5: "CONDITION_TYPE_MFA",
	6: "CONDITION_TYPE_DEVICE_TYPE",
}

var ConditionType_value = map[string]int32{
	"CONDITION_TYPE_UNSPECIFIED":     0,
	"CONDITION_TYPE_TIME_WINDOW":     1,
	"CONDITION_TYPE_LOCATION":        2,
	"CONDITION_TYPE_IP_RANGE":        3,
	"CONDITION_TYPE_CREDENTIAL_TYPE": 4,
	"CONDITION_TYPE_MFA":             5,
	"CONDITION_TYPE_DEVICE_TYPE":     6,
}

func (x ConditionType) String() string {
	return proto.EnumName(ConditionType_name, int32(x))
}

func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{0}
}

// PermissionAction defines types of permission-related actions
type PermissionAction int32

const (
	PermissionAction_PERMISSION_ACTION_UNSPECIFIED PermissionAction = 0
	PermissionAction_PERMISSION_ACTION_GRANT       PermissionAction = 1
	PermissionAction_PERMISSION_ACTION_REVOKE      PermissionAction = 2
	PermissionAction_PERMISSION_ACTION_CHECK       PermissionAction = 3
	PermissionAction_PERMISSION_ACTION_MODIFY      PermissionAction = 4
	PermissionAction_PERMISSION_ACTION_ROLE_ASSIGN PermissionAction = 5
	PermissionAction_PERMISSION_ACTION_ROLE_REMOVE PermissionAction = 6
)

var PermissionAction_name = map[int32]string{
	0: "PERMISSION_ACTION_UNSPECIFIED",
	1: "PERMISSION_ACTION_GRANT",
	2: "PERMISSION_ACTION_REVOKE",
	3: "PERMISSION_ACTION_CHECK",
	4: "PERMISSION_ACTION_MODIFY",
	5: "PERMISSION_ACTION_ROLE_ASSIGN",
	6: "PERMISSION_ACTION_ROLE_REMOVE",
}

var PermissionAction_value = map[string]int32{
	"PERMISSION_ACTION_UNSPECIFIED": 0,
	"PERMISSION_ACTION_GRANT":       1,
	"PERMISSION_ACTION_REVOKE":      2,
	"PERMISSION_ACTION_CHECK":       3,
	"PERMISSION_ACTION_MODIFY":      4,
	"PERMISSION_ACTION_ROLE_ASSIGN": 5,
	"PERMISSION_ACTION_ROLE_REMOVE": 6,
}

func (x PermissionAction) String() string {
	return proto.EnumName(PermissionAction_name, int32(x))
}

func (PermissionAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{1}
}

// Permission defines a bitwise permission set for DID-based access control
type Permission struct {
	// did is the subject DID that holds these permissions
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// resource_type defines what type of resource this permission applies to
	// Examples: "asset", "did", "credential", "device", "zone"
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id is the specific resource identifier (optional, empty means all resources of this type)
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// permission_bits is the bitwise representation of granted permissions
	// Uses uint64 to support up to 64 different permission types
	PermissionBits uint64 `protobuf:"varint,4,opt,name=permission_bits,json=permissionBits,proto3" json:"permission_bits,omitempty"`
	// granted_by is the DID that granted these permissions
	GrantedBy string `protobuf:"bytes,5,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	// granted_at is when the permission was granted
	GrantedAt time.Time `protobuf:"bytes,6,opt,name=granted_at,json=grantedAt,proto3,stdtime" json:"granted_at"`
	// expires_at is when the permission expires (optional, zero time means no expiration)
	ExpiresAt *time.Time `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3,stdtime" json:"expires_at,omitempty"`
	// revoked indicates if this permission has been revoked
	Revoked bool `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// revoked_at is when the permission was revoked
	RevokedAt *time.Time `protobuf:"bytes,9,opt,name=revoked_at,json=revokedAt,proto3,stdtime" json:"revoked_at,omitempty"`
	// revoked_by is the DID that revoked this permission
	RevokedBy string `protobuf:"bytes,10,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	// conditions are optional conditions that must be met for permission to be valid
	Conditions []*PermissionCondition `protobuf:"bytes,11,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// metadata for additional context
	Metadata map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{0}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return m.Size()
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Permission) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Permission) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Permission) GetPermissionBits() uint64 {
	if m != nil {
		return m.PermissionBits
	}
	return 0
}

func (m *Permission) GetGrantedBy() string {
	if m != nil {
		return m.GrantedBy
	}
	return ""
}

func (m *Permission) GetGrantedAt() time.Time {
	if m != nil {
		return m.GrantedAt
	}
	return time.Time{}
}

func (m *Permission) GetExpiresAt() *time.Time {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *Permission) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *Permission) GetRevokedAt() *time.Time {
	if m != nil {
		return m.RevokedAt
	}
	return nil
}

func (m *Permission) GetRevokedBy() string {
	if m != nil {
		return m.RevokedBy
	}
	return ""
}

func (m *Permission) GetConditions() []*PermissionCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Permission) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// PermissionCondition defines a condition that must be met for permission to be valid
type PermissionCondition struct {
	Type ConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=acmain.permission.v1.ConditionType" json:"type,omitempty"`
	// condition_data contains the condition-specific data as JSON
	ConditionData string `protobuf:"bytes,2,opt,name=condition_data,json=conditionData,proto3" json:"condition_data,omitempty"`
}

func (m *PermissionCondition) Reset()         { *m = PermissionCondition{} }
func (m *PermissionCondition) String() string { return proto.CompactTextString(m) }
func (*PermissionCondition) ProtoMessage()    {}
func (*PermissionCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{1}
}
func (m *PermissionCondition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionCondition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionCondition.Merge(m, src)
}
func (m *PermissionCondition) XXX_Size() int {
	return m.Size()
}
func (m *PermissionCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionCondition.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionCondition proto.InternalMessageInfo

func (m *PermissionCondition) GetType() ConditionType {
	if m != nil {
		return m.Type
	}
	return ConditionType_CONDITION_TYPE_UNSPECIFIED
}

func (m *PermissionCondition) GetConditionData() string {
	if m != nil {
		return m.ConditionData
	}
	return ""
}

// PermissionBitDefinition defines the meaning of permission bits for a resource type
type PermissionBitDefinition struct {
	// resource_type is the type of resource this definition applies to
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// bit_position is the bit position (0-63)
	BitPosition uint32 `protobuf:"varint,2,opt,name=bit_position,json=bitPosition,proto3" json:"bit_position,omitempty"`
	// name is the human-readable name of this permission
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// description explains what this permission allows
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// created_at is when this definition was created
	CreatedAt time.Time `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
}

func (m *PermissionBitDefinition) Reset()         { *m = PermissionBitDefinition{} }
func (m *PermissionBitDefinition) String() string { return proto.CompactTextString(m) }
func (*PermissionBitDefinition) ProtoMessage()    {}
func (*PermissionBitDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{2}
}
func (m *PermissionBitDefinition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionBitDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionBitDefinition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionBitDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionBitDefinition.Merge(m, src)
}
func (m *PermissionBitDefinition) XXX_Size() int {
	return m.Size()
}
func (m *PermissionBitDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionBitDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionBitDefinition proto.InternalMessageInfo

func (m *PermissionBitDefinition) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *PermissionBitDefinition) GetBitPosition() uint32 {
	if m != nil {
		return m.BitPosition
	}
	return 0
}

func (m *PermissionBitDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PermissionBitDefinition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PermissionBitDefinition) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

// RolePermission defines a role with associated permission bits
type RolePermission struct {
	// role_name is the unique name of this role
	RoleName string `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	// resource_type defines what type of resource this role applies to
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// permission_bits is the default permission set for this role
	PermissionBits uint64 `protobuf:"varint,3,opt,name=permission_bits,json=permissionBits,proto3" json:"permission_bits,omitempty"`
	// description explains what this role provides
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// created_at is when this role was created
	CreatedAt time.Time `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// updated_at is when this role was last modified
	UpdatedAt *time.Time `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at,omitempty"`
	// created_by is the DID that created this role
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (m *RolePermission) Reset()         { *m = RolePermission{} }
func (m *RolePermission) String() string { return proto.CompactTextString(m) }
func (*RolePermission) ProtoMessage()    {}
func (*RolePermission) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{3}
}
func (m *RolePermission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RolePermission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RolePermission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RolePermission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RolePermission.Merge(m, src)
}
func (m *RolePermission) XXX_Size() int {
	return m.Size()
}
func (m *RolePermission) XXX_DiscardUnknown() {
	xxx_messageInfo_RolePermission.DiscardUnknown(m)
}

var xxx_messageInfo_RolePermission proto.InternalMessageInfo

func (m *RolePermission) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RolePermission) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *RolePermission) GetPermissionBits() uint64 {
	if m != nil {
		return m.PermissionBits
	}
	return 0
}

func (m *RolePermission) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RolePermission) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *RolePermission) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *RolePermission) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// DIDPermissionAssignment assigns permissions to a DID
type DIDPermissionAssignment struct {
	// did is the subject DID
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// permissions are the individual permission grants
	Permissions []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// roles are role assignments for this DID
	Roles []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	// created_at is when this assignment was created
	CreatedAt time.Time `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// updated_at is when this assignment was last modified
	UpdatedAt *time.Time `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at,omitempty"`
}

func (m *DIDPermissionAssignment) Reset()         { *m = DIDPermissionAssignment{} }
func (m *DIDPermissionAssignment) String() string { return proto.CompactTextString(m) }
func (*DIDPermissionAssignment) ProtoMessage()    {}
func (*DIDPermissionAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{4}
}
func (m *DIDPermissionAssignment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DIDPermissionAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DIDPermissionAssignment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DIDPermissionAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DIDPermissionAssignment.Merge(m, src)
}
func (m *DIDPermissionAssignment) XXX_Size() int {
	return m.Size()
}
func (m *DIDPermissionAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_DIDPermissionAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_DIDPermissionAssignment proto.InternalMessageInfo

func (m *DIDPermissionAssignment) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *DIDPermissionAssignment) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *DIDPermissionAssignment) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *DIDPermissionAssignment) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *DIDPermissionAssignment) GetUpdatedAt() *time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

// PermissionAuditLog records permission-related actions for auditing
type PermissionAuditLog struct {
	// id is the unique audit log identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// action describes what permission action occurred
	Action PermissionAction `protobuf:"varint,2,opt,name=action,proto3,enum=acmain.permission.v1.PermissionAction" json:"action,omitempty"`
	// actor_did is the DID that performed the action
	ActorDid string `protobuf:"bytes,3,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	// subject_did is the DID affected by the action
	SubjectDid string `protobuf:"bytes,4,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	// resource_type is the type of resource
	ResourceType string `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id is the specific resource
	ResourceId string `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// permission_bits shows the permission bits involved
	PermissionBits uint64 `protobuf:"varint,7,opt,name=permission_bits,json=permissionBits,proto3" json:"permission_bits,omitempty"`
	// result indicates if the action succeeded
	Result bool `protobuf:"varint,8,opt,name=result,proto3" json:"result,omitempty"`
	// reason provides additional context
	Reason string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	// timestamp is when the action occurred
	Timestamp time.Time `protobuf:"bytes,10,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	// metadata for additional context
	Metadata map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *PermissionAuditLog) Reset()         { *m = PermissionAuditLog{} }
func (m *PermissionAuditLog) String() string { return proto.CompactTextString(m) }
func (*PermissionAuditLog) ProtoMessage()    {}
func (*PermissionAuditLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d8a73046c934a7b, []int{5}
}
func (m *PermissionAuditLog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionAuditLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionAuditLog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionAuditLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionAuditLog.Merge(m, src)
}
func (m *PermissionAuditLog) XXX_Size() int {
	return m.Size()
}
func (m *PermissionAuditLog) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionAuditLog.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionAuditLog proto.InternalMessageInfo

func (m *PermissionAuditLog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PermissionAuditLog) GetAction() PermissionAction {
	if m != nil {
		return m.Action
	}
	return PermissionAction_PERMISSION_ACTION_UNSPECIFIED
}

func (m *PermissionAuditLog) GetActorDid() string {
	if m != nil {
		return m.ActorDid
	}
	return ""
}

func (m *PermissionAuditLog) GetSubjectDid() string {
	if m != nil {
		return m.SubjectDid
	}
	return ""
}

func (m *PermissionAuditLog) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *PermissionAuditLog) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *PermissionAuditLog) GetPermissionBits() uint64 {
	if m != nil {
		return m.PermissionBits
	}
	return 0
}

func (m *PermissionAuditLog) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *PermissionAuditLog) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PermissionAuditLog) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *PermissionAuditLog) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("acmain.permission.v1.ConditionType", ConditionType_name, ConditionType_value)
	proto.RegisterEnum("acmain.permission.v1.PermissionAction", PermissionAction_name, PermissionAction_value)
	proto.RegisterType((*Permission)(nil), "acmain.permission.v1.Permission")
	proto.RegisterMapType((map[string]string)(nil), "acmain.permission.v1.Permission.MetadataEntry")
	proto.RegisterType((*PermissionCondition)(nil), "acmain.permission.v1.PermissionCondition")
	proto.RegisterType((*PermissionBitDefinition)(nil), "acmain.permission.v1.PermissionBitDefinition")
	proto.RegisterType((*RolePermission)(nil), "acmain.permission.v1.RolePermission")
	proto.RegisterType((*DIDPermissionAssignment)(nil), "acmain.permission.v1.DIDPermissionAssignment")
	proto.RegisterType((*PermissionAuditLog)(nil), "acmain.permission.v1.PermissionAuditLog")
	proto.RegisterMapType((map[string]string)(nil), "acmain.permission.v1.PermissionAuditLog.MetadataEntry")
}

func init() {
	proto.RegisterFile("acmain/permission/v1/permission.proto", fileDescriptor_6d8a73046c934a7b)
}

var fileDescriptor_6d8a73046c934a7b = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0x13, 0x27, 0x9b, 0xbc, 0xb4, 0xc1, 0x1a, 0xaa, 0xad, 0xb7, 0x65, 0xd3, 0x6c, 0x56,
	0x0b, 0x65, 0x0f, 0xa9, 0xb6, 0x2b, 0x01, 0x02, 0x09, 0xe4, 0xd8, 0x6e, 0x31, 0xdb, 0xfc, 0x91,
	0x1b, 0xba, 0x5a, 0x2e, 0x96, 0x13, 0xcf, 0x46, 0xa6, 0x8d, 0x1d, 0xd9, 0x93, 0x6a, 0x7d, 0xe3,
	0xce, 0x65, 0x4f, 0x7c, 0x20, 0x4e, 0x7b, 0xdc, 0x23, 0x07, 0x04, 0xa8, 0x15, 0x1f, 0x80, 0x6f,
	0x80, 0x66, 0x3c, 0x76, 0xdc, 0xd6, 0x22, 0x59, 0x09, 0xb8, 0xf9, 0xfd, 0xf9, 0xbd, 0x99, 0xf7,
	0xe6, 0xf7, 0xde, 0x33, 0x3c, 0xb2, 0xc7, 0x53, 0xdb, 0xf5, 0xf6, 0x67, 0x38, 0x98, 0xba, 0x61,
	0xe8, 0xfa, 0xde, 0xfe, 0xc5, 0x93, 0x8c, 0xd4, 0x9e, 0x05, 0x3e, 0xf1, 0xd1, 0x66, 0xec, 0xd6,
	0xce, 0x18, 0x2e, 0x9e, 0x6c, 0xdf, 0x1b, 0xfb, 0xe1, 0xd4, 0x0f, 0x2d, 0xe6, 0xb3, 0x1f, 0x0b,
	0x31, 0x60, 0x7b, 0x73, 0xe2, 0x4f, 0xfc, 0x58, 0x4f, 0xbf, 0xb8, 0x76, 0x77, 0xe2, 0xfb, 0x93,
	0x73, 0xbc, 0xcf, 0xa4, 0xd1, 0xfc, 0xe5, 0x3e, 0x71, 0xa7, 0x38, 0x24, 0xf6, 0x74, 0x16, 0x3b,
	0xb4, 0x7e, 0x28, 0x01, 0x0c, 0xd2, 0x33, 0x90, 0x04, 0x45, 0xc7, 0x75, 0x64, 0xa1, 0x29, 0xec,
	0x55, 0x4d, 0xfa, 0x89, 0x1e, 0xc2, 0x46, 0x80, 0x43, 0x7f, 0x1e, 0x8c, 0xb1, 0x45, 0xa2, 0x19,
	0x96, 0x0b, 0xcc, 0xb6, 0x9e, 0x28, 0x87, 0xd1, 0x0c, 0xa3, 0x5d, 0xa8, 0xa5, 0x4e, 0xae, 0x23,
	0x17, 0x99, 0x0b, 0x24, 0x2a, 0xc3, 0x41, 0x1f, 0xc1, 0x7b, 0x8b, 0x4c, 0xac, 0x91, 0x4b, 0x42,
	0x59, 0x6c, 0x0a, 0x7b, 0xa2, 0x59, 0x5f, 0xa8, 0x3b, 0x2e, 0x09, 0xd1, 0x7d, 0x80, 0x49, 0x60,
	0x7b, 0x04, 0x3b, 0xd6, 0x28, 0x92, 0x4b, 0x2c, 0x50, 0x95, 0x6b, 0x3a, 0x11, 0x52, 0x17, 0x66,
	0x9b, 0xc8, 0xe5, 0xa6, 0xb0, 0x57, 0x3b, 0xd8, 0x6e, 0xc7, 0x49, 0xb6, 0x93, 0x24, 0xdb, 0xc3,
	0x24, 0xc9, 0x4e, 0xe5, 0xcd, 0x6f, 0xbb, 0x6b, 0xaf, 0x7f, 0xdf, 0x15, 0xd2, 0x20, 0x0a, 0x41,
	0x5f, 0x01, 0xe0, 0x57, 0x33, 0x37, 0xc0, 0x21, 0x0d, 0x72, 0x67, 0x69, 0x10, 0x31, 0x0e, 0xc0,
	0x31, 0x0a, 0x41, 0x32, 0xdc, 0x09, 0xf0, 0x85, 0x7f, 0x86, 0x1d, 0xb9, 0xd2, 0x14, 0xf6, 0x2a,
	0x66, 0x22, 0xd2, 0xd0, 0xfc, 0x93, 0x86, 0xae, 0xae, 0x1a, 0x9a, 0x63, 0x14, 0x42, 0xf3, 0x4f,
	0x02, 0x8c, 0x22, 0x19, 0xe2, 0xfc, 0xb9, 0xa6, 0x13, 0x21, 0x03, 0x60, 0xec, 0x7b, 0x8e, 0x4b,
	0x5c, 0xdf, 0x0b, 0xe5, 0x5a, 0xb3, 0xb8, 0x57, 0x3b, 0xf8, 0xb8, 0x9d, 0xc7, 0x95, 0xf6, 0xe2,
	0x55, 0xd5, 0x04, 0x61, 0x66, 0xc0, 0xe8, 0x1b, 0xa8, 0x4c, 0x31, 0xb1, 0x1d, 0x9b, 0xd8, 0xf2,
	0x3a, 0x0b, 0xd4, 0x5e, 0x16, 0xa8, 0xdd, 0xe5, 0x00, 0xdd, 0x23, 0x41, 0x64, 0xa6, 0xf8, 0xed,
	0x2f, 0x60, 0xe3, 0x9a, 0x89, 0xf2, 0xe8, 0x0c, 0x47, 0x09, 0x8f, 0xce, 0x70, 0x84, 0x36, 0xa1,
	0x74, 0x61, 0x9f, 0xcf, 0x13, 0xfe, 0xc4, 0xc2, 0xe7, 0x85, 0xcf, 0x84, 0xd6, 0x1c, 0xde, 0xcf,
	0xb9, 0x2b, 0xfa, 0x14, 0x44, 0xc6, 0x37, 0x1a, 0xa3, 0x7e, 0xf0, 0x30, 0xff, 0x6e, 0xa9, 0x3b,
	0xa5, 0xa1, 0xc9, 0x00, 0xe8, 0x11, 0xd4, 0xd3, 0x34, 0x2d, 0x96, 0x5e, 0x7c, 0xe4, 0x46, 0xaa,
	0xd5, 0x6c, 0x62, 0xb7, 0x7e, 0x15, 0x60, 0x6b, 0x90, 0x25, 0x9f, 0x86, 0x5f, 0xba, 0x5e, 0x7c,
	0xf6, 0x2d, 0xd2, 0x0b, 0x39, 0xa4, 0x7f, 0x00, 0xeb, 0x23, 0x97, 0x58, 0x33, 0x3f, 0x64, 0x20,
	0x76, 0xca, 0x86, 0x59, 0x1b, 0xb9, 0x64, 0xc0, 0x55, 0x08, 0x81, 0xe8, 0xd9, 0x53, 0xcc, 0x1b,
	0x82, 0x7d, 0xa3, 0x26, 0xd4, 0x1c, 0x1c, 0x8e, 0x03, 0x77, 0xc6, 0x50, 0x22, 0x33, 0x65, 0x55,
	0x94, 0xe4, 0xe3, 0x00, 0xdb, 0x9c, 0xe4, 0xa5, 0x77, 0x21, 0x39, 0xc7, 0x29, 0xa4, 0xf5, 0x73,
	0x01, 0xea, 0xa6, 0x7f, 0x8e, 0x33, 0xcd, 0xbd, 0x03, 0xd5, 0xc0, 0x3f, 0xc7, 0x16, 0xbb, 0x52,
	0x9c, 0x51, 0x85, 0x2a, 0x7a, 0xf4, 0x5a, 0x2b, 0xf5, 0x79, 0x4e, 0x1b, 0x17, 0x73, 0xdb, 0xf8,
	0xff, 0x49, 0x92, 0xb6, 0xdb, 0x7c, 0xe6, 0xd8, 0x2b, 0x8f, 0x03, 0xde, 0x6e, 0x1c, 0x13, 0xb7,
	0x5b, 0x72, 0x8b, 0x51, 0xc4, 0x46, 0x41, 0x35, 0x8d, 0xdf, 0x89, 0x5a, 0x3f, 0x16, 0x60, 0x4b,
	0x33, 0xb4, 0x45, 0x0d, 0x95, 0x30, 0x74, 0x27, 0xde, 0x14, 0x7b, 0x24, 0x67, 0x54, 0x76, 0xa0,
	0xb6, 0x28, 0x43, 0x28, 0x17, 0x58, 0x53, 0x35, 0x97, 0x35, 0x95, 0x99, 0x05, 0xd1, 0x36, 0xa1,
	0x4f, 0x42, 0xeb, 0x5a, 0xa4, 0x6d, 0xc2, 0x84, 0x1b, 0xc5, 0x12, 0xff, 0x8d, 0x62, 0x95, 0xde,
	0xb9, 0x58, 0xad, 0x9f, 0x44, 0x40, 0x99, 0x52, 0xcc, 0x1d, 0x97, 0x1c, 0xfb, 0x13, 0x54, 0x87,
	0x42, 0x5a, 0x87, 0x82, 0xeb, 0xa0, 0x2f, 0xa1, 0x6c, 0x8f, 0xd3, 0x8e, 0xa8, 0x1f, 0x7c, 0xb8,
	0xac, 0x02, 0x0a, 0xf3, 0x36, 0x39, 0x8a, 0xd2, 0xd4, 0x1e, 0x13, 0x3f, 0xb0, 0x9c, 0x74, 0x95,
	0x54, 0x98, 0x42, 0x73, 0x1d, 0xba, 0x69, 0xc2, 0xf9, 0xe8, 0x7b, 0x3c, 0x26, 0xcc, 0x1c, 0x13,
	0x0b, 0xb8, 0x4a, 0xcb, 0xdb, 0x57, 0xa5, 0xe5, 0xfb, 0xaa, 0xbc, 0xca, 0xbe, 0xba, 0x93, 0x4b,
	0xf4, 0xbb, 0x50, 0x0e, 0x70, 0x38, 0x3f, 0x27, 0x7c, 0x13, 0x70, 0x29, 0xd6, 0xdb, 0xa1, 0xef,
	0xb1, 0x25, 0x50, 0x35, 0xb9, 0x84, 0x3a, 0x50, 0x4d, 0x57, 0x30, 0x1b, 0xef, 0x2b, 0x3f, 0x64,
	0x0a, 0x43, 0x66, 0x66, 0x72, 0xc7, 0x2b, 0xe0, 0x93, 0xa5, 0x25, 0xe6, 0x8f, 0xf5, 0x9f, 0x4c,
	0xf0, 0xc7, 0x7f, 0x0a, 0xb0, 0x71, 0x6d, 0x12, 0xa3, 0x06, 0x6c, 0xab, 0xfd, 0x9e, 0x66, 0x0c,
	0x8d, 0x7e, 0xcf, 0x1a, 0xbe, 0x18, 0xe8, 0xd6, 0xb7, 0xbd, 0x93, 0x81, 0xae, 0x1a, 0x87, 0x86,
	0xae, 0x49, 0x6b, 0x39, 0xf6, 0xa1, 0xd1, 0xd5, 0xad, 0xe7, 0x46, 0x4f, 0xeb, 0x3f, 0x97, 0x04,
	0xb4, 0x03, 0x5b, 0x37, 0xec, 0xc7, 0x7d, 0x55, 0xa1, 0x92, 0x54, 0xc8, 0x31, 0x1a, 0x03, 0xcb,
	0x54, 0x7a, 0x47, 0xba, 0x54, 0x44, 0x2d, 0x68, 0xdc, 0x30, 0xaa, 0xa6, 0xae, 0xe9, 0xbd, 0xa1,
	0xa1, 0x1c, 0x33, 0x59, 0x12, 0xd1, 0x5d, 0x40, 0x37, 0x7c, 0xba, 0x87, 0x8a, 0x54, 0xca, 0xb9,
	0x95, 0xa6, 0x9f, 0x1a, 0xaa, 0x1e, 0xe3, 0xca, 0x8f, 0xff, 0x12, 0x40, 0xba, 0x49, 0x5b, 0xf4,
	0x00, 0xee, 0x0f, 0x74, 0xb3, 0x6b, 0x9c, 0x9c, 0x50, 0x94, 0xa2, 0x32, 0xf0, 0xf5, 0x6c, 0x77,
	0x60, 0xeb, 0xb6, 0xcb, 0x91, 0xa9, 0xf4, 0x86, 0x92, 0x80, 0x3e, 0x00, 0xf9, 0xb6, 0xd1, 0xd4,
	0x4f, 0xfb, 0xcf, 0xf4, 0x38, 0xd7, 0xdb, 0x56, 0xf5, 0x6b, 0x5d, 0x7d, 0x26, 0x15, 0xf3, 0xa1,
	0xdd, 0xbe, 0x66, 0x1c, 0xbe, 0x90, 0xc4, 0xfc, 0x8b, 0x99, 0xfd, 0x63, 0xdd, 0x52, 0x4e, 0x4e,
	0x8c, 0xa3, 0x9e, 0x54, 0xfa, 0x07, 0x17, 0x53, 0xef, 0xf6, 0x4f, 0x75, 0xa9, 0xdc, 0x79, 0xfa,
	0xe6, 0xb2, 0x21, 0xbc, 0xbd, 0x6c, 0x08, 0x7f, 0x5c, 0x36, 0x84, 0xd7, 0x57, 0x8d, 0xb5, 0xb7,
	0x57, 0x8d, 0xb5, 0x5f, 0xae, 0x1a, 0x6b, 0xdf, 0xdd, 0xe3, 0x7f, 0xb2, 0xaf, 0xb2, 0xff, 0xb2,
	0xb4, 0xe5, 0xc2, 0x51, 0x99, 0x51, 0xf9, 0xe9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x59,
	0x15, 0x31, 0xed, 0x0a, 0x00, 0x00,
}

func (m *Permission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Permission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Permission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintPermission(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintPermission(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintPermission(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.Conditions) > 0 {
		for iNdEx := len(m.Conditions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Conditions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPermission(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.RevokedBy) > 0 {
		i -= len(m.RevokedBy)
		copy(dAtA[i:], m.RevokedBy)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.RevokedBy)))
		i--
		dAtA[i] = 0x52
	}
	if m.RevokedAt != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RevokedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintPermission(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x4a
	}
	if m.Revoked {
		i--
		if m.Revoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.ExpiresAt != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ExpiresAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiresAt):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintPermission(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x3a
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.GrantedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.GrantedAt):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintPermission(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x32
	if len(m.GrantedBy) > 0 {
		i -= len(m.GrantedBy)
		copy(dAtA[i:], m.GrantedBy)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.GrantedBy)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PermissionBits != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.PermissionBits))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ResourceId) > 0 {
		i -= len(m.ResourceId)
		copy(dAtA[i:], m.ResourceId)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ResourceType) > 0 {
		i -= len(m.ResourceType)
		copy(dAtA[i:], m.ResourceType)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PermissionCondition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionCondition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionCondition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConditionData) > 0 {
		i -= len(m.ConditionData)
		copy(dAtA[i:], m.ConditionData)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ConditionData)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PermissionBitDefinition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionBitDefinition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionBitDefinition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintPermission(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BitPosition != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.BitPosition))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ResourceType) > 0 {
		i -= len(m.ResourceType)
		copy(dAtA[i:], m.ResourceType)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RolePermission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RolePermission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RolePermission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x3a
	}
	if m.UpdatedAt != nil {
		n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedAt):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintPermission(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x32
	}
	n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintPermission(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x2a
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.PermissionBits != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.PermissionBits))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ResourceType) > 0 {
		i -= len(m.ResourceType)
		copy(dAtA[i:], m.ResourceType)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RoleName) > 0 {
		i -= len(m.RoleName)
		copy(dAtA[i:], m.RoleName)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.RoleName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DIDPermissionAssignment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DIDPermissionAssignment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DIDPermissionAssignment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedAt != nil {
		n7, err7 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UpdatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedAt):])
		if err7 != nil {
			return 0, err7
		}
		i -= n7
		i = encodeVarintPermission(dAtA, i, uint64(n7))
		i--
		dAtA[i] = 0x2a
	}
	n8, err8 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err8 != nil {
		return 0, err8
	}
	i -= n8
	i = encodeVarintPermission(dAtA, i, uint64(n8))
	i--
	dAtA[i] = 0x22
	if len(m.Roles) > 0 {
		for iNdEx := len(m.Roles) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Roles[iNdEx])
			copy(dAtA[i:], m.Roles[iNdEx])
			i = encodeVarintPermission(dAtA, i, uint64(len(m.Roles[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Permissions) > 0 {
		for iNdEx := len(m.Permissions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Permissions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPermission(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PermissionAuditLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionAuditLog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionAuditLog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		for k := range m.Metadata {
			v := m.Metadata[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintPermission(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintPermission(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintPermission(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	n9, err9 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err9 != nil {
		return 0, err9
	}
	i -= n9
	i = encodeVarintPermission(dAtA, i, uint64(n9))
	i--
	dAtA[i] = 0x52
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Result {
		i--
		if m.Result {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.PermissionBits != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.PermissionBits))
		i--
		dAtA[i] = 0x38
	}
	if len(m.ResourceId) > 0 {
		i -= len(m.ResourceId)
		copy(dAtA[i:], m.ResourceId)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ResourceType) > 0 {
		i -= len(m.ResourceType)
		copy(dAtA[i:], m.ResourceType)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ResourceType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SubjectDid) > 0 {
		i -= len(m.SubjectDid)
		copy(dAtA[i:], m.SubjectDid)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.SubjectDid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ActorDid) > 0 {
		i -= len(m.ActorDid)
		copy(dAtA[i:], m.ActorDid)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.ActorDid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Action != 0 {
		i = encodeVarintPermission(dAtA, i, uint64(m.Action))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPermission(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPermission(dAtA []byte, offset int, v uint64) int {
	offset -= sovPermission(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Permission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.ResourceType)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.ResourceId)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.PermissionBits != 0 {
		n += 1 + sovPermission(uint64(m.PermissionBits))
	}
	l = len(m.GrantedBy)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.GrantedAt)
	n += 1 + l + sovPermission(uint64(l))
	if m.ExpiresAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ExpiresAt)
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.Revoked {
		n += 2
	}
	if m.RevokedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RevokedAt)
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.RevokedBy)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if len(m.Conditions) > 0 {
		for _, e := range m.Conditions {
			l = e.Size()
			n += 1 + l + sovPermission(uint64(l))
		}
	}
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovPermission(uint64(len(k))) + 1 + len(v) + sovPermission(uint64(len(v)))
			n += mapEntrySize + 1 + sovPermission(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *PermissionCondition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovPermission(uint64(m.Type))
	}
	l = len(m.ConditionData)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	return n
}

func (m *PermissionBitDefinition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ResourceType)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.BitPosition != 0 {
		n += 1 + sovPermission(uint64(m.BitPosition))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovPermission(uint64(l))
	return n
}

func (m *RolePermission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RoleName)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.ResourceType)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.PermissionBits != 0 {
		n += 1 + sovPermission(uint64(m.PermissionBits))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovPermission(uint64(l))
	if m.UpdatedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedAt)
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	return n
}

func (m *DIDPermissionAssignment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if len(m.Permissions) > 0 {
		for _, e := range m.Permissions {
			l = e.Size()
			n += 1 + l + sovPermission(uint64(l))
		}
	}
	if len(m.Roles) > 0 {
		for _, s := range m.Roles {
			l = len(s)
			n += 1 + l + sovPermission(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovPermission(uint64(l))
	if m.UpdatedAt != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedAt)
		n += 1 + l + sovPermission(uint64(l))
	}
	return n
}

func (m *PermissionAuditLog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.Action != 0 {
		n += 1 + sovPermission(uint64(m.Action))
	}
	l = len(m.ActorDid)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.SubjectDid)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.ResourceType)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = len(m.ResourceId)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	if m.PermissionBits != 0 {
		n += 1 + sovPermission(uint64(m.PermissionBits))
	}
	if m.Result {
		n += 2
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovPermission(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovPermission(uint64(l))
	if len(m.Metadata) > 0 {
		for k, v := range m.Metadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovPermission(uint64(len(k))) + 1 + len(v) + sovPermission(uint64(len(v)))
			n += mapEntrySize + 1 + sovPermission(uint64(mapEntrySize))
		}
	}
	return n
}

func sovPermission(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPermission(x uint64) (n int) {
	return sovPermission(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Permission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Permission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Permission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermissionBits", wireType)
			}
			m.PermissionBits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PermissionBits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrantedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GrantedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GrantedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.GrantedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiresAt == nil {
				m.ExpiresAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ExpiresAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revoked = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RevokedAt == nil {
				m.RevokedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RevokedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevokedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conditions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Conditions = append(m.Conditions, &PermissionCondition{})
			if err := m.Conditions[len(m.Conditions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPermission
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPermission
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthPermission
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthPermission
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPermission
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthPermission
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthPermission
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPermission(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthPermission
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermissionCondition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionCondition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionCondition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ConditionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConditionData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConditionData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermissionBitDefinition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionBitDefinition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionBitDefinition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitPosition", wireType)
			}
			m.BitPosition = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BitPosition |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RolePermission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RolePermission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RolePermission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermissionBits", wireType)
			}
			m.PermissionBits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PermissionBits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DIDPermissionAssignment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DIDPermissionAssignment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DIDPermissionAssignment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permissions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Permissions = append(m.Permissions, &Permission{})
			if err := m.Permissions[len(m.Permissions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roles = append(m.Roles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedAt == nil {
				m.UpdatedAt = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermissionAuditLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionAuditLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionAuditLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			m.Action = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Action |= PermissionAction(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubjectDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubjectDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermissionBits", wireType)
			}
			m.PermissionBits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PermissionBits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Result = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPermission
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPermission
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPermission
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPermission
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthPermission
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthPermission
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPermission
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthPermission
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthPermission
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipPermission(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthPermission
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Metadata[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPermission(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPermission
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPermission(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPermission
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPermission
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPermission
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPermission
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPermission
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPermission        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPermission          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPermission = fmt.Errorf("proto: unexpected end of group")
)
